/** AUTO-GENERATED by scripts/extract-userguide-cards.mjs — не править вручную */
export declare const USER_GUIDE_CARDS: readonly [{
    readonly label: "ABSZ";
    readonly title: "ABSZ";
    readonly syntax: "ABSZ list";
    readonly description: "Список материалов типа A. Те же правила ввода, что и для строки FISZ. Может отсутствовать.";
    readonly fragment: "burnup";
}, {
    readonly label: "ACEPT";
    readonly title: "ACEPT";
    readonly syntax: "ACEPT …";
    readonly description: "включение/выключение в подмодуле FARION для расчёта резонансного";
    readonly fragment: "physical";
}, {
    readonly label: "ACERR";
    readonly title: "ACERR";
    readonly syntax: "ACERR valacerr";
    readonly description: "[PHOT valphot] [WPHO valwpho] [IWPHN valiwphn] [EGPH valegph1,valegph2] [ELEC valelec] [EGEL valegel1,valegel2] [PSIN valpsin] [PSGR valpsgr] [MATFIL list] [MATPRN] [SIPRN] [DEFPRN] [MATWGT] [MATREP] [VOL V1, V2,..., Vn,..., Vnmat] [STOP]";
    readonly fragment: "physical";
}, {
    readonly label: "ACTI";
    readonly title: "ACTI";
    readonly syntax: "ACTI list";
    readonly description: "Указание о выводе на печать характеристик продуктов деления. Те же правила ввода, что и для строки CONT.";
    readonly fragment: "burnup";
}, {
    readonly label: "ADDF";
    readonly title: "ADDF";
    readonly syntax: "ADDF file";
    readonly description: "Определяет название файла file, в котором пользователем задается изот опный состав дополнительного топлива. Единица измерения – число ядер на кубический сантиметр материала в сутки. Формат этого файла ясен из примера на рисунке А.95. PU39 1.739E-06 PU40 8.687E-07 PU41 2.889E-07 Рисунок А.95 – Формат файла задания скорости подпитки Исходные данные опции FINAL 15.2 Опция позволяет получить концентрацию изотопов при временах, не совпадающих с временами, определенными в файле исходных данных VAR.DAT при работе с опцией STEP. В представлении кусочно -линейной зависимости (см отри описание карты COLI)";
    readonly fragment: "burnup";
}, {
    readonly label: "ADDZ";
    readonly title: "ADDZ";
    readonly syntax: "ADDZ m";
    readonly description: "Определяет номер материала m, в который с постоянной скоростью вводятся новые изотопы. По умолчанию эта строка не задаётся и новые изотопы не вводятся. Очистка и подпитка топлива может выполняться в одном или разных материалах.";
    readonly fragment: "burnup";
}, {
    readonly label: "BAL";
    readonly title: "BAL";
    readonly syntax: "BAL …";
    readonly description: "при наличии этой карты будут вычисляться функционалы баланса";
    readonly fragment: "registration";
}, {
    readonly label: "BCRIT";
    readonly title: "BCRIT";
    readonly syntax: "BCRIT value";
    readonly description: "[EABS] [MNEN list] [ZNEN list] [ONEN list] [MPHEN list] [ZPHEN list] [OPHEN list] [MELEN list] [ZELEN list] [OELEN list] [NUCOFF] [PERC value1] [FIXED] [NRET value1 value2]";
    readonly fragment: "registration";
}, {
    readonly label: "BETA";
    readonly title: "BETA";
    readonly syntax: "BETA";
    readonly description: "При наличии карты вычисляется эффективная доля запаздывающих нейтронов. Редактированию не подлежит.";
    readonly fragment: "calculationControl";
}, {
    readonly label: "BMAX";
    readonly title: "BMAX";
    readonly syntax: "BMAX maxbur";
    readonly description: "[VOL V1, V2,..., Vn,..., Vnmat] [BUCL value1 value2 value3] FINISH commentary";
    readonly fragment: "burnupRegistration";
}, {
    readonly label: "BOUN";
    readonly title: "BOUN";
    readonly syntax: "BOUN   <mi,ni>   <mj,nj>";
    readonly description: "Здесь <mi,ni> - пара целых чисел, которые определяют диапазон изменения первого индекса i, <mj,nj> - пара целых чисел, которые определяют диапазон изменения второго индекса j. ROOT <массив из трех чисел> <массив из трех чисел> < массив из трех чисел > Здесь <массив из трех чисел> - это параметры, которые задают три вектора A, B, C. Векторы сдвигов решетки образуются по правилу (Рисунок А.81): ⃗ = ⃗ + i ⃗⃗ + j ⃗ (i = mi, mi + 1,..., ni) (j = mj, mj + 1,..., nj). -1 0 1 2 3 4 5 4 3 2 1 0 A 0 B C Рисунок А.81 – Задание решетки примитивных источников";
    readonly fragment: "source";
}, {
    readonly label: "BRG";
    readonly title: "BRG";
    readonly syntax: "BRG [value1 value2]";
    readonly description: "BRG – заголовок исходных данных к модулю, первая обязательная карта. value1 - определяет наличие/отсутствие печати карт файла исходных данных в выходном файле (1 – печатать, 0 – не печатать). Значение по умолчанию – 0. value2 - определяет наличие/отсутствие отладочной печати в выходном файле, а при наличии печати также и ее количество (больше 0 – печатать, 0 – не печатать). Значение по умолчанию – 0. Если после заголовка нет ни одной карты, то в этом случае модуль не работает.";
    readonly fragment: "burnupRegistration";
}, {
    readonly label: "BUCL";
    readonly title: "BUCL";
    readonly syntax: "BUCL Bx, By, Bz";
    readonly description: "[BCRIT value] [EABS] [MNEN list] [ZNEN list] [ONEN list] [MPHEN list] [ZPHEN list] [OPHEN list] [MELEN list] [ZELEN list] [OELEN list] [NUCOFF] [PERC value1] [FIXED] [NRET value1 value2]";
    readonly fragment: "burnupRegistration";
}, {
    readonly label: "BURALL";
    readonly title: "BURALL";
    readonly syntax: "BURALL …";
    readonly description: "использованием карты BURALL позволяет наиболее полно использовать возможности";
    readonly fragment: "burnupRegistration";
}, {
    readonly label: "CLEF";
    readonly title: "CLEF";
    readonly syntax: "CLEF file";
    readonly description: "Определяет название файла file, в котором пользователем задается период полувыведения для разны х элементов, который характеризует скорость очистки и является полным аналогом периода полураспада радиоактивных ядер. Формат этого файла ясен из примера на рисунке А.94. Xe 1.0 h Sr 30.0 d Eu 0.2 y Рисунок А.94 – Формат файла задания скорости очистки Введено ограничение: для элементов с временем полувыведения менее 10 часов оно принудительно устанавливается равным 10 часам, а рассчитанная плотность для данного нуклида принудительно устанавливается равной 10–20. Если элемент в file не задан, то он из активной зоны не выводится.";
    readonly fragment: "burnup";
}, {
    readonly label: "CLEZ";
    readonly title: "CLEZ";
    readonly syntax: "CLEZ m";
    readonly description: "Определяет номер материала m, подлежащего очистке. По умолчанию эта строка не задаётся и очистка не выполняется.";
    readonly fragment: "burnup";
}, {
    readonly label: "CNTAND";
    readonly title: "CNTAND";
    readonly syntax: "CNTAND …";
    readonly description: "картой CONT в файле исходных данных должна быть использована карта CNTAND.";
    readonly fragment: "geometry";
}, {
    readonly label: "CODE";
    readonly title: "CODE";
    readonly syntax: "CODE option";
    readonly description: "Определяет название используемой опции работы модуля. Наличие этой строки обязательно. option – может принимать следующие значения:  RSTP – используется опция STEP;";
    readonly fragment: "burnup";
}, {
    readonly label: "COLI";
    readonly title: "COLI";
    readonly syntax: "COLI …";
    readonly description: "В представлении кусочно -линейной зависимости (см отри описание карты COLI)";
    readonly fragment: "burnup";
}, {
    readonly label: "CONT";
    readonly title: "CONT";
    readonly syntax: "CONT list";
    readonly description: "Указание о выводе на печать характеристик всех изотопов. Список list содержит указатели для вывода характеристик:  DENS – концентрация;  SIGM – макроскопическое сечение.  CURI – активность;  HEAT – энерговыделение при радиоактивном распаде;  HGAM – энергия гамма квантов при радиоактивном распаде;  HBET – энергия тормозного излучения электронов и позитронов при радиоактивном распаде  QUOT – объем воды, нужный для разбавления изотопа до допустимой концентрации;  SPNU – число нейтронов спонтанного деления и (alpha,n) реакции; Элементы списка могут следовать в произвольном порядке; любой элемент может";
    readonly fragment: "geometry";
}, {
    readonly label: "CPM";
    readonly title: "CPM";
    readonly syntax: "CPM …";
    readonly description: "физического модуля добавлены карты CPM и CPMEND для обозначения начала и конца";
    readonly fragment: "physical";
}, {
    readonly label: "DEF";
    readonly title: "DEF";
    readonly syntax: "DEF …";
    readonly description: "Все карты DEF должны располагаться в разделе данных для физического модуля.";
    readonly fragment: "physical";
}, {
    readonly label: "DEFPRN";
    readonly title: "DEFPRN";
    readonly syntax: "DEFPRN …";
    readonly description: "печатаются параметры нуклидов с учетом переопределений, сделанных";
    readonly fragment: "physical";
}, {
    readonly label: "DELN";
    readonly title: "DELN";
    readonly syntax: "DELN valdeln";
    readonly description: "[ACEPT] [ACERR valacerr] [PHOT valphot] [WPHO valwpho] [IWPHN valiwphn] [EGPH valegph1,valegph2] [ELEC valelec] [EGEL valegel1,valegel2] [PSIN valpsin] [PSGR valpsgr] [MATFIL list] [MATPRN] [SIPRN] [DEFPRN] [MATWGT] [MATREP] [VOL V1, V2,..., Vn,..., Vnmat] [STOP]";
    readonly fragment: "registration";
}, {
    readonly label: "DOS";
    readonly title: "DOS";
    readonly syntax: "DOS list";
    readonly description: "[ENERGY list] [SPECTR value] [SFLUX] [DPNT x1,y1,z1,R1,…,xN,yN,zN,RN] [DRING x1,y1,z1,r1,R1,…,xN,yN,zN,rN,RN] [NENRG A, E1,…,EN] [NFUNC A, F1,…,FN] [PENRG A, E1,…,EN] [PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.";
    readonly fragment: "registration";
}, {
    readonly label: "DPNT";
    readonly title: "DPNT";
    readonly syntax: "DPNT x1,y1,z1,R1,…,xN,yN,zN,RN";
    readonly description: "[DRING x1,y1,z1,r1,R1,…,xN,yN,zN,rN,RN] [NENRG A, E1,…,EN] [NFUNC A, F1,…,FN] [PENRG A, E1,…,EN] [PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.";
    readonly fragment: "registration";
}, {
    readonly label: "DRING";
    readonly title: "DRING";
    readonly syntax: "DRING x1,y1,z1,r1,R1,…,xN,yN,zN,rN,RN";
    readonly description: "[NENRG A, E1,…,EN] [NFUNC A, F1,…,FN] [PENRG A, E1,…,EN] [PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.";
    readonly fragment: "registration";
}, {
    readonly label: "DTZM";
    readonly title: "DTZM";
    readonly syntax: "DTZM nser";
    readonly description: "nser - количество серий, через которое накопленная информация записывается в файл задачи; может редактироваться в процессе счета.";
    readonly fragment: "calculationControl";
}, {
    readonly label: "EABS";
    readonly title: "EABS";
    readonly syntax: "EABS …";
    readonly description: "при наличии этой карты вычисляется средняя энергия поглощения";
    readonly fragment: "registration";
}, {
    readonly label: "ECEL";
    readonly title: "ECEL";
    readonly syntax: "ECEL e1";
    readonly description: "Указывается граница энергии электрона в электронвольтах, ниже которой траектории прерываются. Область изменения параметра оп ределяется диапазоном работы фотонного подмодуля, заданным в разделе исходных данных для физического модуля. Значение по умолчанию – 100 эВ. Может редактироваться в процессе счета. Управление неаналоговым моделированием 14.2 Допустимо использование нескольких а льтернативных методов неаналогового моделирования. Какой из них будет использован определяется ключами генерации. Для нейтронов и фотонов используется один и тот же метод, но парметры для разных типов частиц могут быть разными.";
    readonly fragment: "calculationControl";
}, {
    readonly label: "ECPO";
    readonly title: "ECPO";
    readonly syntax: "ECPO e1";
    readonly description: "Нижняя граница энергии позитрона (эВ); траектории ниже прерываются. Аналог ECUT/ECUP/ECEL для позитронов. По умолчанию как у электронов — 100 эВ. Редактируется в процессе счёта.";
    readonly fragment: "calculationControl";
}, {
    readonly label: "ECUP";
    readonly title: "ECUP";
    readonly syntax: "ECUP e1";
    readonly description: "Указывается граница энергии фотона в электронвольтах, ниже которой траектории прерываются. Область изменения параметра определяется диапазоном работы фотонного подмодуля, заданным в разделе исходных данных для физического модуля. Значение по умолчанию – 10000 эВ. Может редактироваться в процессе счета.";
    readonly fragment: "calculationControl";
}, {
    readonly label: "ECUT";
    readonly title: "ECUT";
    readonly syntax: "ECUT e1";
    readonly description: "Указывается граница энергии нейтрона в электронвольтах, ниже которой траектории прерываются. Область изменения параметра определяется диапазоном работы нейтронных подмодулей, заданных в разделе исходных данных для физического модуля. Значение по умолчанию – 0 эВ. Может редактироваться в процессе счета.";
    readonly fragment: "calculationControl";
}, {
    readonly label: "EDIS";
    readonly title: "EDIS";
    readonly syntax: "EDIS …";
    readonly description: "случайной величины одинаковы и равны числу NE из карты EDIS или NM из карты MDIS,";
    readonly fragment: "source";
}, {
    readonly label: "EGEL";
    readonly title: "EGEL";
    readonly syntax: "EGEL valegel1,valegel2";
    readonly description: "[PSIN valpsin] [PSGR valpsgr] [MATFIL list] [MATPRN] [SIPRN] [DEFPRN] [MATWGT] [MATREP] [VOL V1, V2,..., Vn,..., Vnmat] [STOP]";
    readonly fragment: "physical";
}, {
    readonly label: "EGPH";
    readonly title: "EGPH";
    readonly syntax: "EGPH valegph1,valegph2";
    readonly description: "[ELEC valelec] [EGEL valegel1,valegel2] [PSIN valpsin] [PSGR valpsgr] [MATFIL list] [MATPRN] [SIPRN] [DEFPRN] [MATWGT] [MATREP] [VOL V1, V2,..., Vn,..., Vnmat] [STOP]";
    readonly fragment: "physical";
}, {
    readonly label: "EGRC";
    readonly title: "EGRC";
    readonly syntax: "EGRC …";
    readonly description: "имя управляющего массива параметров, определяющего энергетические";
    readonly fragment: "physical";
}, {
    readonly label: "ELEC";
    readonly title: "ELEC";
    readonly syntax: "ELEC valelec";
    readonly description: "[EGEL valegel1,valegel2] [PSIN valpsin] [PSGR valpsgr] [MATFIL list] [MATPRN] [SIPRN] [DEFPRN] [MATWGT] [MATREP] [VOL V1, V2,..., Vn,..., Vnmat] [STOP]";
    readonly fragment: "physical";
}, {
    readonly label: "EMES";
    readonly title: "EMES";
    readonly syntax: "EMES   <массив значений узлов>";
    readonly description: "MMES <массив значений узлов> <массив значений узлов> - действительные числа, определяющие узлы возможных значений величины Е в карте EMES или узлы возможных значений величины  в карте MMES. Значения узлов всегд а вводят в порядке возрастания. Значения Е всегда неотрицательны, значения  могут меняться от –1 до 1 (как косинус угла). Массивы вероятностей вводятся с помощью карт: EPRO <массив значений вероятностей> MPRO <массив значений вероятностей> <массив значений вероятностей> - действительные числа, определяющие значения вероятностей для величины Е в карте EPRO или значения вероятностей для величины  в";
    readonly fragment: "source";
}, {
    readonly label: "END";
    readonly title: "END";
    readonly syntax: "END …";
    readonly description: "имя карты окончания описания материала. Эта карта может быть";
}, {
    readonly label: "ENERGY";
    readonly title: "ENERGY";
    readonly syntax: "ENERGY list";
    readonly description: "[SPECTR value] [SFLUX] [DPNT x1,y1,z1,R1,…,xN,yN,zN,RN] [DRING x1,y1,z1,r1,R1,…,xN,yN,zN,rN,RN] [NENRG A, E1,…,EN] [NFUNC A, F1,…,FN] [PENRG A, E1,…,EN] [PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.";
    readonly fragment: "registration";
}, {
    readonly label: "ENSO";
    readonly title: "ENSO";
    readonly syntax: "ENSO <число>";
    readonly description: "FINISH X,Y,Z - координаты точки источника, задаваемые в сантиметрах. За начало координат принимается начало отсчета, определенное в данных к геометрическому модулю. <массив из 27 чисел> - числа определяют границы энергетических интервалов, данных в убывающем порядке. Энергия задается в электронвольтах. В результате работы источника";
    readonly fragment: "source";
}, {
    readonly label: "EOPT";
    readonly title: "EOPT";
    readonly syntax: "EOPT opt";
    readonly description: "Устанавливается способ задания значения энерговыделения при делении, opt может принимать значения: 0 – эффективная энергия, 1 – сумма энергий реакций деления и радиационного захвата. Строка может отсутствовать. Значение по умолчанию равно 0.";
    readonly fragment: "burnup";
}, {
    readonly label: "EPRO";
    readonly title: "EPRO";
    readonly syntax: "EPRO   <массив значений вероятностей>";
    readonly description: "MPRO <массив значений вероятностей> <массив значений вероятностей> - действительные числа, определяющие значения вероятностей для величины Е в карте EPRO или значения вероятностей для величины  в карте MPRO. Данные, содержащиеся во всех этих массивах, зависят от характеристик спектра, заданного в картах ANGLEN, EDIS, MDIS. Возможны следующие варианты задания параметров в картах дополнительных данных для дискретного и линейного распределений. а) Независимые случайные величины с дискретным распределением (параметр NO или отсутствие этого параметра в карте ANGLEN, параметр D в картах EDIS, MDIS)";
    readonly fragment: "source";
}, {
    readonly label: "EPSM";
    readonly title: "EPSM";
    readonly syntax: "EPSM eps";
    readonly description: "eps – минимальное значение концентрации изотопов при передаче информации в MCU. Если концентрация изотопа меньше, чем eps, то в MCU этот изотоп не передается. Если eps = 0, передаются все изотопы с концентрацией, отличной от нуля. Если eps < 0, передаются все изотопы, в том числе и с концентрацией, равной нулю. Строка может отсутствовать, в этом случае используется стандартн ое значение (eps=0.0), задаваемое при генерации модуля.";
    readonly fragment: "burnup";
}, {
    readonly label: "ESET";
    readonly title: "ESET";
    readonly syntax: "ESET <массив из 27 чисел>";
    readonly description: "[SPEC <массив из 26 чисел>] [ENSO <число>] FINISH X,Y,Z - координаты точки источника, задаваемые в сантиметрах. За начало координат принимается начало отсчета, определенное в данных к геометрическому модулю. <массив из 27 чисел> - числа определяют границы энергетических интервалов, данных в убывающем порядке. Энергия задается в электронвольтах. В результате работы источника";
    readonly fragment: "source";
}, {
    readonly label: "FINISH";
    readonly title: "FINISH";
    readonly syntax: "FINISH [commentary]";
    readonly description: "Здесь FINISH - признак окончания ввода данных к физическому модулю. commentary - текст произвольного содержания. Коррекция данных с помощью файлов PDC 8.10 При работе с исходными данными для физическ ого модуля возможно выполнить коррекцию некоторых данных с помощью внешних текстовых файлов с расширениями вида PDCn (PIN Data Correction), где n может принимать значения от 1 до 9 или отсутствовать (соответствует n=0). При наличии таких фалов в папке с ра счетом их обработка выполняется автоматически. Обработка производится в порядке увеличения n, т.е. в первую очередь будет обработан файл с расширением PDC, а в последнюю – PDC9.";
}, {
    readonly label: "FISP";
    readonly title: "FISP";
    readonly syntax: "FISP list";
    readonly description: "Указание о выводе на печать характеристик продуктов деления. Те же правила, что и для строки CONT.";
    readonly fragment: "burnup";
}, {
    readonly label: "FISZ";
    readonly title: "FISZ";
    readonly syntax: "FISZ list";
    readonly description: "Список материалов типа F. Параметр list определяет номера материалов типа F. Номера материалов в списке list указываются интервалами. Нечетные числа обозначают начала интервалов, четные – их окончания. На рисунке А.88 приведены примеры задания материалов с типом F. Пример 1. Тип F задан для материала 3. FISZ 3 Пример 2. Тип F задан для материала 3. FISZ 3 3 Пример 3. Тип F задан для материалов 3, с 5 по 8, 15. FISZ 3 3, 5 8, 15 Рисунок А.88 – Примеры задания типа материала";
    readonly fragment: "burnup";
}, {
    readonly label: "FIXED";
    readonly title: "FIXED";
    readonly syntax: "FIXED …";
    readonly description: "при наличии этой карты создается файл, содержащий результаты работы";
    readonly fragment: "registration";
}, {
    readonly label: "GLIB";
    readonly title: "GLIB";
    readonly syntax: "GLIB library";
    readonly description: "Задает названия библиотеки выходов гамма-квантов. library – имя библиотеки, записанной в файле с указанным именем. При отсутствии этого параметра, расчет производится со стандартной библиотекой. Имя стандартной библиотеки задается при генерации модуля. Исходные данные опций FINTAB и DELTAB 15.4 Опция FINTAB предназначена для постобработки и печати результатов работы STEP и FINAL. Выводятся результаты последнего обращения к FINAL, а если обращения не было, то результаты опции STEP. Постобработка включает в себя расчет следующих интегральных характ еристик материалов и системы в целом:  мощность, кВт;";
    readonly fragment: "burnup";
}, {
    readonly label: "HEAD";
    readonly title: "HEAD";
    readonly syntax: "HEAD [<целое число 1>[<целое число 2>[<целое число 3>]]]";
    readonly description: "Обязательной в этом предложении является только метка HEAD. <целое число 1> принимает значения 0,1,2,3,4 (значение по умолчанию есть 1):";
    readonly fragment: "geometry";
}, {
    readonly label: "HGRI";
    readonly title: "HGRI";
    readonly syntax: "HGRI   <массив чисел>";
    readonly description: "<массив чисел> - массив действительных чисел, задающий положения hi Если Nh <0, то вводятся Nh возможных значений высоты: h1 < h2 <...< hM; (M = Nh) Если Nh >0, то вводятся концы Nh отрезков: h0 < h1 < h2 <...< hM. Внутри каждого из этих отрезков случайная величина равномерно распределена. HPC <массив чисел> <массив чисел> - массив из пар чисел ( vi,fi). Числа vi означают реальные интенсивности моделируемого источника. Числа fi означают с точностью до множителя вероятности, с которыми будут генерироваться частицы. Два следующих предложения определяют распределение ri и зависимость весов от";
    readonly fragment: "source";
}, {
    readonly label: "HPC";
    readonly title: "HPC";
    readonly syntax: "HPC   <массив чисел>";
    readonly description: "<массив чисел> - массив из пар чисел ( vi,fi). Числа vi означают реальные интенсивности моделируемого источника. Числа fi означают с точностью до множителя вероятности, с которыми будут генерироваться частицы. Два следующих предложения определяют распределение ri и зависимость весов от r. RGRI <массив чисел> <массив чисел> - массив действительных чисел, задающий положения ri.";
    readonly fragment: "source";
}, {
    readonly label: "ICE";
    readonly title: "ICE";
    readonly syntax: "ICE list";
    readonly description: "ICE - имя заголовка раздела; list – список элементов, подлежащих разложению на изотопы. [ICENOT list]";
    readonly fragment: "physical";
}, {
    readonly label: "ICENOT";
    readonly title: "ICENOT";
    readonly syntax: "ICENOT list";
    readonly description: "ICENOT - имя заголовка раздела; list – список элементов, не подлежащих разложению на изотопы. Список действует с момента его объявления. Можно использовать любое количество карт разложения на изотопы. Это позволяет задавать разложение на изотопы независимо для каждого материала. Можно использовать карту без указания списка. В этом случае с этого м омента разложение на изотопы не производится. Разложение на изотопы производится в соответствии с данными файла ICE.LIB банка данных, который добавлен в MDBFR61. Для разложения на изотопы всех элементов, рекомендуется использовать строку «ICENOT AAAA».";
    readonly fragment: "physical";
}, {
    readonly label: "INPE";
    readonly title: "INPE";
    readonly syntax: "INPE  <массив ценностей>";
    readonly description: "<массив ценностей> - массив положительных действительных чисел. Число этих чисел должно быть таким же, как число отрезков. Ценности регистрационных объектов задаются предложением INPO <массив ценностей> <массив ценностей> - массив положительных действительных чисел. Длина этого массива может не совпадать с реальным числом регистрационных объектов. Если длина массива меньше этого числа, недостающие позиции заполняются единицами. Режим расщепления/рулетки включается в файл параметров с расширением MEM по ключу +SPLRUL. Режим не совмещается с режимом весового окна и с режимом поверхностного источника.";
    readonly fragment: "calculationControl";
}, {
    readonly label: "INPM";
    readonly title: "INPM";
    readonly syntax: "INPM  < массив из NR*NE чисел >";
    readonly description: "<массив из NR*NE чисел> – массив понимается как матрица VEij вводимая по строкам и определяющая ценности по радиусам и энергиям. SANG < массив косинусов > <массив косинусов> – вводится массив их NA -1 чисел -1<s1<s2<…<sNA-1<1 Определяет разбиение пространства по углам. (NА-1 - размерность массива). INRA < массив из NR*NA чисел > <массив из NR*NA чисел> – массив понимается как матрица VA размерности NR*NA, вводимая по строкам. Последние 2 предложения могут отсутствовать. При отсут ствии этих карт зависимость от направления полёта отсутствует. При угловом разбиении и сферической системе координат весовые окна";
    readonly fragment: "trajectory";
}, {
    readonly label: "INPO";
    readonly title: "INPO";
    readonly syntax: "INPO  <массив ценностей>";
    readonly description: "<массив ценностей> - массив положительных действительных чисел. Длина этого массива может не совпадать с реальным числом регистрационных объектов. Если длина массива меньше этого числа, недостающие позиции заполняются единицами. Режим расщепления/рулетки включается в файл параметров с расширением MEM по ключу +SPLRUL. Режим не совмещается с режимом весового окна и с режимом поверхностного источника.";
    readonly fragment: "calculationControl";
}, {
    readonly label: "INRA";
    readonly title: "INRA";
    readonly syntax: "INRA  < массив из NR*NA чисел >";
    readonly description: "<массив из NR*NA чисел> – массив понимается как матрица VA размерности NR*NA, вводимая по строкам. Последние 2 предложения могут отсутствовать. При отсут ствии этих карт зависимость от направления полёта отсутствует. При угловом разбиении и сферической системе координат весовые окна определены следующим алгоритмом. Пусть точка фазового пространства имеет координаты (X,E,U). X – геометрическое положение, E – энергия, U – направление полёта. Числа j, k, n определены так, что выполнены соотношения: Тогда параметр w m окна определён выражением w m=1/(VEjkVAjn) и w i=wm/ci, ws=wi/cs. При использовании цилиндрической системы используются те же самые формулы,";
    readonly fragment: "trajectory";
}, {
    readonly label: "ISTR";
    readonly title: "ISTR";
    readonly syntax: "ISTR istr";
    readonly description: "Число istr определяет тип решаемой задачи. По умолчанию istr = 0. В этом случае решается задача о критичности системы и вычисляется эффективный коэффициент размножения. При istr = 1 решается задача с заданным внешним источником. При istr = 2 решается задача с заданным внешним источником и блокируется использование нейтронов деления. Этот режим предназначен для задач, в которых используется рассчитанная каким-то другим методом плотность нейтронов деления.";
    readonly fragment: "trajectory";
}, {
    readonly label: "IWPHN";
    readonly title: "IWPHN";
    readonly syntax: "IWPHN valiwphn";
    readonly description: "[EGPH valegph1,valegph2] [ELEC valelec] [EGEL valegel1,valegel2] [PSIN valpsin] [PSGR valpsgr] [MATFIL list] [MATPRN] [SIPRN] [DEFPRN] [MATWGT] [MATREP] [VOL V1, V2,..., Vn,..., Vnmat] [STOP]";
    readonly fragment: "physical";
}, {
    readonly label: "KEFF";
    readonly title: "KEFF";
    readonly syntax: "KEFF …";
    readonly description: "(необходимо наличие карты KEFF) для value значений параметра Bz (необходимо наличие";
    readonly fragment: "registration";
}, {
    readonly label: "LATT";
    readonly title: "LATT";
    readonly syntax: "LATT   <имя генератора сдвигов>";
    readonly description: "Здесь <имя генератора сдвигов> - S2AR Структура дальнейших строк зависит от используемого генератора сдвигов. В настоящее время реализован только один такой генератор, называющийся S2AR, исходные данные для которого будут описаны. Этот генератор соответствует правильной параллелограммной решетке, подобной генерируемой генератором сдвигов G2AR в модуле NCG. Входные данные состоят из следующих строк. BOUN <mi,ni> <mj,nj> Здесь <mi,ni> - пара целых чисел, которые определяют диапазон изменения первого индекса i, <mj,nj> - пара целых чисел, которые определяют диапазон изменения второго индекса j.";
}, {
    readonly label: "LIFE";
    readonly title: "LIFE";
    readonly syntax: "LIFE …";
    readonly description: "при наличии этой карты будет рассчитываться среднее время жизни";
    readonly fragment: "registration";
}, {
    readonly label: "LIST";
    readonly title: "LIST";
    readonly syntax: "LIST list";
    readonly description: "PARA list В строке LIST задается список изотопов, а в строке PARA задаются их характеристики. Элемент в списке строки LIST задается его химическим символом, а изотоп – в обозначениях MCU. Характеристики в списке строки PARA задаются по тем же правилам, что и для карты CONT. При отсутствии этой карты на печать выводится только концентрация (DENS). На рисунке А.96 приведены примеры задания списка изотопов картой LIST.";
    readonly fragment: "burnup";
}, {
    readonly label: "MATFIL";
    readonly title: "MATFIL";
    readonly syntax: "MATFIL list";
    readonly description: "[MATPRN] [SIPRN] [DEFPRN] [MATWGT] [MATREP] [VOL V1, V2,..., Vn,..., Vnmat] [STOP]";
    readonly fragment: "physical";
}, {
    readonly label: "MATPRN";
    readonly title: "MATPRN";
    readonly syntax: "MATPRN …";
    readonly description: "по окончании ввода для каждого материала в формате исходных";
    readonly fragment: "physical";
}, {
    readonly label: "MATR";
    readonly title: "MATR";
    readonly syntax: "MATR …";
    readonly description: "пропущена, если следующей картой является карта MATR или карта FINISH.";
    readonly fragment: "physical";
}, {
    readonly label: "MATREP";
    readonly title: "MATREP";
    readonly syntax: "MATREP …";
    readonly description: "осуществляет замену состава всех материалов на первый из отоп";
    readonly fragment: "physical";
}, {
    readonly label: "MATWGT";
    readonly title: "MATWGT";
    readonly syntax: "MATWGT …";
    readonly description: "рассчитывается вес каждого материала в граммах. Готовится";
    readonly fragment: "physical";
}, {
    readonly label: "MAXS";
    readonly title: "MAXS";
    readonly syntax: "MAXS maxser";
    readonly description: "maxser –номер серии, после которой счет прекращается; может редактироваться в процессе счета. При наличии ненулевого количества отбрасываемых серий (карта NSKI) параметр maxser определяет число регистрируемых серий, т. е. счет окончится после моделирования числа серий, равного сумме параметров карт NSKI и MAXS.";
    readonly fragment: "calculationControl";
}, {
    readonly label: "MCUR";
    readonly title: "MCUR";
    readonly syntax: "MCUR list";
    readonly description: "[ZCUR list] [OCUR list] [MSMT list] [ZSMT list] [OSMT list] [RCT list] [FRM list] [DOS list] [ENERGY list] [SPECTR value] [SFLUX] [DPNT x1,y1,z1,R1,…,xN,yN,zN,RN] [DRING x1,y1,z1,r1,R1,…,xN,yN,zN,rN,RN] [NENRG A, E1,…,EN] [NFUNC A, F1,…,FN] [PENRG A, E1,…,EN] [PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.";
    readonly fragment: "registration";
}, {
    readonly label: "MDOS";
    readonly title: "MDOS";
    readonly syntax: "MDOS …";
    readonly description: "эти карты определяют номера регистрационных областей";
    readonly fragment: "registration";
}, {
    readonly label: "MELEN";
    readonly title: "MELEN";
    readonly syntax: "MELEN list";
    readonly description: "[ZELEN list] [OELEN list] [NUCOFF] [PERC value1] [FIXED] [NRET value1 value2]";
    readonly fragment: "registration";
}, {
    readonly label: "MFLU";
    readonly title: "MFLU";
    readonly syntax: "MFLU list";
    readonly description: "[ZFLU list] [OFLU list] [LEAK] [MIGL] [MRCT list] [ZRCT list] [ORCT list] [MDOS list] [ZDOS list] [ODOS list] [MPOW value1]";
    readonly fragment: "registration";
}, {
    readonly label: "MIR";
    readonly title: "MIR";
    readonly syntax: "MIR …";
    readonly description: "1,-1,0 1";
    readonly fragment: "geometry";
}, {
    readonly label: "MIXG";
    readonly title: "MIXG";
    readonly syntax: "MIXG nmixg";
    readonly description: "Карта управляет нормализацией поколений в многопроцессорном режиме. При nmixg = 0 нормализация выполняется независимо на каждом процессоре, что соответствует стандартной идеологии распараллеливания расчетов MCU. При n mixg отличном от нуля после, того как все процессоры промоделировали одно поколение нейтронов, выполняется сбор данных по всем процессорам, общая нормализация и раздача нормализованных данных процессорам. Таким образом, в этом режиме многопроцессорный расчет полностью аналогичен по идеологии обычному однопроцессорному расчету. По умолчанию nmixg = 0. FINISH Признак конца фрагмента.";
    readonly fragment: "trajectory";
}, {
    readonly label: "MMES";
    readonly title: "MMES";
    readonly syntax: "MMES  <массив значений узлов>";
    readonly description: "<массив значений узлов> - действительные числа, определяющие узлы возможных значений величины Е в карте EMES или узлы возможных значений величины  в карте MMES. Значения узлов всегд а вводят в порядке возрастания. Значения Е всегда неотрицательны, значения  могут меняться от –1 до 1 (как косинус угла). Массивы вероятностей вводятся с помощью карт: EPRO <массив значений вероятностей> MPRO <массив значений вероятностей> <массив значений вероятностей> - действительные числа, определяющие значения вероятностей для величины Е в карте EPRO или значения вероятностей для величины  в карте MPRO. Данные, содержащиеся во всех этих массивах, зависят от характеристик спектра,";
    readonly fragment: "source";
}, {
    readonly label: "MNEN";
    readonly title: "MNEN";
    readonly syntax: "MNEN list";
    readonly description: "[ZNEN list] [ONEN list] [MPHEN list] [ZPHEN list] [OPHEN list] [MELEN list] [ZELEN list] [OELEN list] [NUCOFF] [PERC value1] [FIXED] [NRET value1 value2]";
    readonly fragment: "registration";
}, {
    readonly label: "MOM4";
    readonly title: "MOM4";
    readonly syntax: "MOM4 …";
    readonly description: "при наличии этой карты помимо первого и второго центральных";
    readonly fragment: "registration";
}, {
    readonly label: "MPHEN";
    readonly title: "MPHEN";
    readonly syntax: "MPHEN list";
    readonly description: "[ZPHEN list] [OPHEN list] [MELEN list] [ZELEN list] [OELEN list] [NUCOFF] [PERC value1] [FIXED] [NRET value1 value2]";
    readonly fragment: "registration";
}, {
    readonly label: "MPRO";
    readonly title: "MPRO";
    readonly syntax: "MPRO   <массив значений вероятностей>";
    readonly description: "<массив значений вероятностей> - действительные числа, определяющие значения вероятностей для величины Е в карте EPRO или значения вероятностей для величины  в карте MPRO. Данные, содержащиеся во всех этих массивах, зависят от характеристик спектра, заданного в картах ANGLEN, EDIS, MDIS. Возможны следующие варианты задания параметров в картах дополнительных данных для дискретного и линейного распределений. а) Независимые случайные величины с дискретным распределением (параметр NO или отсутствие этого параметра в карте ANGLEN, параметр D в картах EDIS, MDIS) Длины <массива значений узлов> и <массива значений вероятностей> для каждой";
    readonly fragment: "source";
}, {
    readonly label: "MRCT";
    readonly title: "MRCT";
    readonly syntax: "MRCT list";
    readonly description: "[ZRCT list] [ORCT list] [MDOS list] [ZDOS list] [ODOS list] [MPOW value1]";
    readonly fragment: "registration";
}, {
    readonly label: "NAMV";
    readonly title: "NAMV";
    readonly syntax: "NAMV namvar";
    readonly description: "namvar - название варианта; текстовая переменная длиной не более 12 символов; редактированию не подлежит.";
    readonly fragment: "calculationControl";
}, {
    readonly label: "NBAT";
    readonly title: "NBAT";
    readonly syntax: "NBAT nbatch";
    readonly description: "Каждые последовательные nbatch поколений частиц, называемых сериями, считаются независимыми. По умолчанию nbatch = 3. Точность расчета статистических ошибок рассчитываемых функционалов возрастает с увеличением nbatch.";
    readonly fragment: "trajectory";
}, {
    readonly label: "NENRG";
    readonly title: "NENRG";
    readonly syntax: "NENRG A, E1,…,EN";
    readonly description: "[NFUNC A, F1,…,FN] [PENRG A, E1,…,EN] [PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.";
    readonly fragment: "registration";
}, {
    readonly label: "NET";
    readonly title: "NET";
    readonly syntax: "NET  <имя сети>   <корневой вектор> <число столбцов>";
    readonly description: "<число строк>[<число слоев>]";
    readonly fragment: "geometry";
}, {
    readonly label: "NEUT";
    readonly title: "NEUT";
    readonly syntax: "NEUT valneut";
    readonly description: "EGRC valegrc1, valegrc2, valegrc3 [DELN valdeln] [ACEPT] [ACERR valacerr] [PHOT valphot] [WPHO valwpho] [IWPHN valiwphn] [EGPH valegph1,valegph2] [ELEC valelec] [EGEL valegel1,valegel2] [PSIN valpsin] [PSGR valpsgr] [MATFIL list] [MATPRN] [SIPRN] [DEFPRN] [MATWGT] [MATREP] [VOL V1, V2,..., Vn,..., Vnmat] [STOP]";
    readonly fragment: "physical";
}, {
    readonly label: "NFUNC";
    readonly title: "NFUNC";
    readonly syntax: "NFUNC A, F1,…,FN";
    readonly description: "[PENRG A, E1,…,EN] [PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.";
    readonly fragment: "registration";
}, {
    readonly label: "NPRI";
    readonly title: "NPRI";
    readonly syntax: "NPRI nhys";
    readonly description: "nhys - количество историй, через которое на экран будет поступать информационная строка; может редактироваться в процессе счета. BETA При наличии этой карты вычисляется эффективная доля запаздывающих нейтронов; редактированию не подлежит.";
    readonly fragment: "calculationControl";
}, {
    readonly label: "NRAN";
    readonly title: "NRAN";
    readonly syntax: "NRAN n";
    readonly description: "Параметр, управляющий началом выборки случайных чисел; используется для продолжения расчетов при фатальных авостах; для продолжения счета нужно вновь";
    readonly fragment: "calculationControl";
}, {
    readonly label: "NRET";
    readonly title: "NRET";
    readonly syntax: "NRET value1 value2";
    readonly description: "KEFF – при наличии этой карты будет рассчитываться эффективный коэффициент размножения нейтронов в рассчитываемой системе.";
    readonly fragment: "registration";
}, {
    readonly label: "NSKI";
    readonly title: "NSKI";
    readonly syntax: "NSKI nski";
    readonly description: "Число отбрасываемых серий, т. е. серий, не учитываемых при накоплен ии статистики. По умолчанию nski = 0. WTOB w1, w2, ... , wkobj Данная карта предназначена для использования при корректировке числа нейтронов деления на один акт деления (однако распространяется на все типы моделируемых частиц). Карта содержит массив wi, где i соответствует номеру регистрационного объекта. Каждое wi есть неотрицательное число, на которое умножается вес любой вторичной частицы, рожденной в регистрационном объекте i, перед помещением ее в банк. При wi=0 вторичные частицы , рожденные в регис трационном";
    readonly fragment: "trajectory";
}, {
    readonly label: "NTOT";
    readonly title: "NTOT";
    readonly syntax: "NTOT ntot";
    readonly description: "Число частиц в поколении. По умолчанию ntot = 200. Систематическая ошибка расчета функционалов убывает обратно пропорционально ntot.";
    readonly fragment: "trajectory";
}, {
    readonly label: "NUCOFF";
    readonly title: "NUCOFF";
    readonly syntax: "NUCOFF …";
    readonly description: "при наличии этой карты регистрация скоростей реакций для нуклидов в";
    readonly fragment: "registration";
}, {
    readonly label: "OCUR";
    readonly title: "OCUR";
    readonly syntax: "OCUR list";
    readonly description: "[MSMT list] [ZSMT list] [OSMT list] [RCT list] [FRM list] [DOS list] [ENERGY list] [SPECTR value] [SFLUX] [DPNT x1,y1,z1,R1,…,xN,yN,zN,RN] [DRING x1,y1,z1,r1,R1,…,xN,yN,zN,rN,RN] [NENRG A, E1,…,EN] [NFUNC A, F1,…,FN] [PENRG A, E1,…,EN] [PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.";
    readonly fragment: "registration";
}, {
    readonly label: "ODOS";
    readonly title: "ODOS";
    readonly syntax: "ODOS …";
    readonly description: "эти карты определяют номера регистрационных областей";
    readonly fragment: "registration";
}, {
    readonly label: "OELEN";
    readonly title: "OELEN";
    readonly syntax: "OELEN list";
    readonly description: "[NUCOFF] [PERC value1] [FIXED] [NRET value1 value2]";
    readonly fragment: "registration";
}, {
    readonly label: "OFLU";
    readonly title: "OFLU";
    readonly syntax: "OFLU list";
    readonly description: "[LEAK] [MIGL] [MRCT list] [ZRCT list] [ORCT list] [MDOS list] [ZDOS list] [ODOS list] [MPOW value1]";
    readonly fragment: "registration";
}, {
    readonly label: "ONEN";
    readonly title: "ONEN";
    readonly syntax: "ONEN list";
    readonly description: "[MPHEN list] [ZPHEN list] [OPHEN list] [MELEN list] [ZELEN list] [OELEN list] [NUCOFF] [PERC value1] [FIXED] [NRET value1 value2]";
    readonly fragment: "registration";
}, {
    readonly label: "OPHEN";
    readonly title: "OPHEN";
    readonly syntax: "OPHEN list";
    readonly description: "[MELEN list] [ZELEN list] [OELEN list] [NUCOFF] [PERC value1] [FIXED] [NRET value1 value2]";
    readonly fragment: "registration";
}, {
    readonly label: "ORCT";
    readonly title: "ORCT";
    readonly syntax: "ORCT …";
    readonly description: "эти карты определяют номера регистрационных областей";
    readonly fragment: "registration";
}, {
    readonly label: "PARA";
    readonly title: "PARA";
    readonly syntax: "PARA list";
    readonly description: "В строке LIST задается список изотопов, а в строке PARA задаются их характеристики. Элемент в списке строки LIST задается его химическим символом, а изотоп – в обозначениях MCU. Характеристики в списке строки PARA задаются по тем же правилам, что и для карты CONT. При отсутствии этой карты на печать выводится только концентрация (DENS). На рисунке А.96 приведены примеры задания списка изотопов картой LIST.";
    readonly fragment: "burnup";
}, {
    readonly label: "PARM";
    readonly title: "PARM";
    readonly syntax: "PARM …";
    readonly description: "P0XY,-P0XY,2.5 /2 -P0XY,P0XY,2.5 P0XY,P0XY,2.5";
    readonly fragment: "geometry";
}, {
    readonly label: "PBUR";
    readonly title: "PBUR";
    readonly syntax: "PBUR extention";
    readonly description: "Определяет расширение файла PARAMETE.*, хранящегося в библиотеке констант в директории BURN6. Данные файлы содержат цепочки превращения нуклидов в ходе выгорания при разных реакциях взаимодействия с нейтронами и выходы продуктов деления для быстрого ( PARAMETE.FST) и теплового ( PARAMETE.THR) спектров нейтронов. Наличие этой стро ки необязательно, если используется файл, имя которого задано при генерации модуля, т.е. значение по умолчанию. extention – может принимать значения FST или THR. Умалчиваемое значение – THR. По умолчанию расчетный код «настроен» на тепловые реакторы, для р асчета быстрых систем необходимо воспользоваться картой PBUR со значением FST.";
    readonly fragment: "burnup";
}, {
    readonly label: "PENRG";
    readonly title: "PENRG";
    readonly syntax: "PENRG A, E1,…,EN";
    readonly description: "[PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.";
    readonly fragment: "registration";
}, {
    readonly label: "PERC";
    readonly title: "PERC";
    readonly syntax: "PERC …";
    readonly description: "Примечание. Карты PERC, FIXED, NRET используются только на этапе финальной";
    readonly fragment: "registration";
}, {
    readonly label: "PFUNC";
    readonly title: "PFUNC";
    readonly syntax: "PFUNC A, F1,…,FN";
    readonly description: "END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.";
    readonly fragment: "registration";
}, {
    readonly label: "PHOT";
    readonly title: "PHOT";
    readonly syntax: "PHOT valphot";
    readonly description: "[WPHO valwpho] [IWPHN valiwphn] [EGPH valegph1,valegph2] [ELEC valelec] [EGEL valegel1,valegel2] [PSIN valpsin] [PSGR valpsgr] [MATFIL list] [MATPRN] [SIPRN] [DEFPRN] [MATWGT] [MATREP] [VOL V1, V2,..., Vn,..., Vnmat] [STOP]";
    readonly fragment: "physical";
}, {
    readonly label: "PIN";
    readonly title: "PIN";
    readonly syntax: "PIN [value1 value2]";
    readonly description: "Здесь PIN - имя карты — заголовка фрагмента; value1 - определяет наличие /отсутствие печати карт файла исходных данных в выходном файле (1 – печатать, 0 – не печатать). Значение по умолчанию — 0. value2 - определяет наличие/отсутствие отладочной печати в выходном файле, а при наличии печати также и ее количество (0 – не печатать, 1,2,… – печатать). Значение по умолчанию — 0. При значении этого параметра равном";
    readonly fragment: "physical";
}, {
    readonly label: "POWE";
    readonly title: "POWE";
    readonly syntax: "POWE q";
    readonly description: "Устанавливается режим работы \"заданная мощность\" и, одновременно задается суммарное по всем материалам энерговыделение q. Данная карта является, по сут и, картой POWE опции STEP в которой используется только первое значение мощности, а последующие значения времени и мощности игнорируются. Единицы измерения: q – кВт. BSEC t BMIN t BHOU t BDAY t Эти строки задают время t работы на мощности q для расчета и вывода на печать концентрации изотопов и данных о запаздывающем излучении. Единицы измерения, соответственно, BSEC – секунда, BMIN – минута, BHOU – час, BDAY – сутки. Опция требует наличия карты STEP, хотя и не использует ее значений.";
    readonly fragment: "burnup";
}, {
    readonly label: "POWZ";
    readonly title: "POWZ";
    readonly syntax: "POWZ list";
    readonly description: "Список материалов типа P. Те же правила ввода, что и для раздела FISZ. Может отсутствовать. Одна из строк FISZ или ABSZ со списком материалов должна присутствовать обязательно, иначе будет выдано сообщение об ошибке. POWE q1 t1 q2 t2 q3 t3 ... Устанавливается режим работы \"заданная мощность\" и, одновременно задается суммарное по всем материалам энерговыделение Q в зависимости от времени T. Единицы измерения: Q – кВт, T – сутки. Q(T) представляется как кусочно -постоянная функция и вводится парами чисел q (энерговыделение на данном временном интервале) и t (верхняя граница временного интервала).";
    readonly fragment: "burnup";
}, {
    readonly label: "PRISOU";
    readonly title: "PRISOU";
    readonly syntax: "PRISOU …";
    readonly description: "Карта PRISOU включает печать внутренних массивов модуля источников.";
    readonly fragment: "source";
}, {
    readonly label: "PSGR";
    readonly title: "PSGR";
    readonly syntax: "PSGR valpsgr";
    readonly description: "[MATFIL list] [MATPRN] [SIPRN] [DEFPRN] [MATWGT] [MATREP] [VOL V1, V2,..., Vn,..., Vnmat] [STOP]";
    readonly fragment: "physical";
}, {
    readonly label: "PSIN";
    readonly title: "PSIN";
    readonly syntax: "PSIN valpsin";
    readonly description: "[PSGR valpsgr] [MATFIL list] [MATPRN] [SIPRN] [DEFPRN] [MATWGT] [MATREP] [VOL V1, V2,..., Vn,..., Vnmat] [STOP]";
    readonly fragment: "physical";
}, {
    readonly label: "PTYPE";
    readonly title: "PTYPE";
    readonly syntax: "PTYPE …";
    readonly description: "обязательная первая карта раздела.";
    readonly fragment: "registration";
}, {
    readonly label: "RADS";
    readonly title: "RADS";
    readonly syntax: "RADS  <массив радиусов слоёв >";
    readonly description: "<массив радиусов слоёв> – массив действительных, положительных чисел: r1<r2<…<rNR. (NR- размерность массива). 1-ый слой определён неравенством 0rr1, j-ый слой определён неравенством rj-1<rrj. INPM < массив из NR*NE чисел > <массив из NR*NE чисел> – массив понимается как матрица VEij вводимая по строкам и определяющая ценности по радиусам и энергиям. SANG < массив косинусов > <массив косинусов> – вводится массив их NA -1 чисел -1<s1<s2<…<sNA-1<1 Определяет разбиение пространства по углам. (NА-1 - размерность массива). INRA < массив из NR*NA чисел > <массив из NR*NA чисел> – массив понимается как матрица VA размерности";
    readonly fragment: "trajectory";
}, {
    readonly label: "RCT";
    readonly title: "RCT";
    readonly syntax: "RCT list";
    readonly description: "[FRM list] [DOS list] [ENERGY list] [SPECTR value] [SFLUX] [DPNT x1,y1,z1,R1,…,xN,yN,zN,RN] [DRING x1,y1,z1,r1,R1,…,xN,yN,zN,rN,RN] [NENRG A, E1,…,EN] [NFUNC A, F1,…,FN] [PENRG A, E1,…,EN] [PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.";
    readonly fragment: "registration";
}, {
    readonly label: "RCZD";
    readonly title: "RCZD";
    readonly syntax: "RCZD …";
    readonly description: "означает цилиндр с внутренним распределением вероятностей рождения.";
    readonly fragment: "source";
}, {
    readonly label: "REPER";
    readonly title: "REPER";
    readonly syntax: "REPER  <массив параметров>";
    readonly description: "<массив параметров>:  три действительных числа, задающие координаты постоянного реперного вектора, который нормируется на свою длину.  /P и три действительных числа, которые задают координаты характерной точки системы ⃗ (положение индикатора). В этом случае при рождении частицы реперный вектор в точке рождения определяется по формуле ⃗p = ( ⃗ – ⃗) ( ⃗ – ⃗, ⃗ – ⃗)-0.5  число 1 либо минус 1, которое определяет знак нормали, то есть sgn. При каждой генерации точки рождения примитивный источник вырабатывает зависящий от этой точки вектор нормали к контейнеру vn . Реперный вектор определяется по формуле";
    readonly fragment: "source";
}, {
    readonly label: "RGRI";
    readonly title: "RGRI";
    readonly syntax: "RGRI   <массив чисел>";
    readonly description: "<массив чисел> - массив действительных чисел, задающий положения ri.";
    readonly fragment: "source";
}, {
    readonly label: "RGS";
    readonly title: "RGS";
    readonly syntax: "RGS [value1 value2]";
    readonly description: "RGS - имя карты — заголовка фрагмента; value1 - определяет наличие/отсутствие печати карт файла исходных данных в выходном файле (1 – печатать, 0 – не печатать). Значение по умолчанию — 0. value2 - определяет наличие/отсутствие отладочной печати в выходном файле, а при наличии печати также и ее количество (больше 0 – печатать, 0 – не печатать). Значение по умолчанию — 0.";
    readonly fragment: "registration";
}, {
    readonly label: "SANG";
    readonly title: "SANG";
    readonly syntax: "SANG  < массив косинусов >";
    readonly description: "<массив косинусов> – вводится массив их NA -1 чисел -1<s1<s2<…<sNA-1<1 Определяет разбиение пространства по углам. (NА-1 - размерность массива). INRA < массив из NR*NA чисел > <массив из NR*NA чисел> – массив понимается как матрица VA размерности NR*NA, вводимая по строкам. Последние 2 предложения могут отсутствовать. При отсут ствии этих карт зависимость от направления полёта отсутствует. При угловом разбиении и сферической системе координат весовые окна определены следующим алгоритмом. Пусть точка фазового пространства имеет координаты (X,E,U). X – геометрическое положение, E – энергия, U – направление полёта.";
    readonly fragment: "trajectory";
}, {
    readonly label: "SETT";
    readonly title: "SETT";
    readonly syntax: "SETT np";
    readonly description: "Управляющий параметр np может принимать значения N, PH , EL, PO. (по умолчанию np равно N). Значение N означает что все дальнейшие строки данных для неаналогового моделирования относятся к нейтронам, значение PH – к фотонам, EL – к электронам, PO – к позитронам. Таким образом, если решается чисто нейтронная задача, то строка задания типа частицы не нужна.";
    readonly fragment: "calculationControl";
}, {
    readonly label: "SFLUX";
    readonly title: "SFLUX";
    readonly syntax: "SFLUX …";
    readonly description: "текущем разделе параметров регистрации (карты SFLUX + MCUR, ZCUR и/или OCUR)";
    readonly fragment: "registration";
}, {
    readonly label: "SI";
    readonly title: "SI";
    readonly syntax: "SI list";
    readonly description: "Здесь SI - имя заголовка раздела; list – список нуклидов, входящих в суммарный изотоп. [SINOT list] Здесь SINOT - имя заголовка раздела; list – список нуклидов, не входящих в суммарный изотоп. [SIDEN value] Здесь SIDEN - имя заголовка раздела; value – все нуклиды с плотностью меньше данного значения входят в суммарный изотоп. Список действует с момента его объявления. Можно использовать любое количество карт описания суммарного изотопа. Это позволяет задавать состав суммарного изотопа независимо для каждого материала. Можно использовать карту без указания списка. В этом случае, считается, что с этого момента суммарный изотоп не содержит";
    readonly fragment: "physical";
}, {
    readonly label: "SIDEN";
    readonly title: "SIDEN";
    readonly syntax: "SIDEN value";
    readonly description: "Здесь SIDEN - имя заголовка раздела; value – все нуклиды с плотностью меньше данного значения входят в суммарный изотоп. Список действует с момента его объявления. Можно использовать любое количество карт описания суммарного изотопа. Это позволяет задавать состав суммарного изотопа независимо для каждого материала. Можно использовать карту без указания списка. В этом случае, считается, что с этого момента суммарный изотоп не содержит нуклидов. При одно временном наличии перед описанием материала списков SI и SINOT активным является тот, который был объявлен последним. Карта SIDEN активна всегда, независимо от наличия или отсутствия карт SI и";
    readonly fragment: "physical";
}, {
    readonly label: "SINOT";
    readonly title: "SINOT";
    readonly syntax: "SINOT list";
    readonly description: "Здесь SINOT - имя заголовка раздела; list – список нуклидов, не входящих в суммарный изотоп. [SIDEN value] Здесь SIDEN - имя заголовка раздела; value – все нуклиды с плотностью меньше данного значения входят в суммарный изотоп. Список действует с момента его объявления. Можно использовать любое количество карт описания суммарного изотопа. Это позволяет задавать состав суммарного изотопа независимо для каждого материала. Можно использовать карту без указания списка. В этом случае, считается, что с этого момента суммарный изотоп не содержит нуклидов. При одно временном наличии перед описанием материала списков SI и SINOT";
    readonly fragment: "physical";
}, {
    readonly label: "SIPRN";
    readonly title: "SIPRN";
    readonly syntax: "SIPRN …";
    readonly description: "для каждого материала печатаются сечения полученн ого суммарного";
    readonly fragment: "physical";
}, {
    readonly label: "SPEC";
    readonly title: "SPEC";
    readonly syntax: "SPEC <массив из 26 чисел>";
    readonly description: "[ENSO <число>] FINISH X,Y,Z - координаты точки источника, задаваемые в сантиметрах. За начало координат принимается начало отсчета, определенное в данных к геометрическому модулю. <массив из 27 чисел> - числа определяют границы энергетических интервалов, данных в убывающем порядке. Энергия задается в электронвольтах. В результате работы источника";
    readonly fragment: "source";
}, {
    readonly label: "SPECTR";
    readonly title: "SPECTR";
    readonly syntax: "SPECTR value";
    readonly description: "[SFLUX] [DPNT x1,y1,z1,R1,…,xN,yN,zN,RN] [DRING x1,y1,z1,r1,R1,…,xN,yN,zN,rN,RN] [NENRG A, E1,…,EN] [NFUNC A, F1,…,FN] [PENRG A, E1,…,EN] [PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.";
    readonly fragment: "registration";
}, {
    readonly label: "SPNT";
    readonly title: "SPNT";
    readonly syntax: "SPNT …";
    readonly description: "Признаком использования простого источника является карта SPNT, которая";
    readonly fragment: "source";
}, {
    readonly label: "STEP";
    readonly title: "STEP";
    readonly syntax: "STEP …";
    readonly description: "Опция требует наличия карты STEP, хотя и не использует ее значений.";
}, {
    readonly label: "STOP";
    readonly title: "STOP";
    readonly syntax: "STOP …";
    readonly description: "останавливает выполнение задачи после окончания чтения исходных";
}, {
    readonly label: "SUMZ";
    readonly title: "SUMZ";
    readonly syntax: "SUMZ list";
    readonly description: "Указание о выводе на печать интегральных характеристик всей системы и отдельных материалов. Список list содержит указатели для вывода характеристик:  SUMB – характеристики выгорания всей системы;  ZONB – характеристики выгорания отдельных материалов;  SUMS – макроскопические сечения всей системы;";
    readonly fragment: "burnup";
}, {
    readonly label: "TEMPR";
    readonly title: "TEMPR";
    readonly syntax: "TEMPR value";
    readonly description: "TEMPR - имя заголовка раздела; value - значение температуры, константа вещественного типа. Описание суммарного изотопа 8.5 В разделе описания суммарного изотопа задается список нуклидов, входящих в суммарный изотоп. Нуклиды, входящие в суммарный изотоп, обрабатываются иначе, чем нуклиды, не входящ ие в него. В суммарный изотоп обычно помещаются нуклиды, не оказывающие значительного влияния на результаты моделирования конкретной системы. Метод основан на том, что в каждом материале пользователь может заменить малозначащие изотопы (продукты деления и далёкие актиноиды) одним суммарным изотопом с нулевыми сечениями рассеяния и деления и сечениями поглощения и";
    readonly fragment: "physical";
}, {
    readonly label: "THOU";
    readonly title: "THOU";
    readonly syntax: "THOU …";
    readonly description: "час, TDAY – сутки, TYEA – год. Отсчет времени задается строкой TIMP.";
    readonly fragment: "burnup";
}, {
    readonly label: "TRANSF";
    readonly title: "TRANSF";
    readonly syntax: "TRANSF …";
    readonly description: "На рисунке А.37 приводится пример использования карты TRANSF.";
}, {
    readonly label: "TTYPE";
    readonly title: "TTYPE";
    readonly syntax: "TTYPE value1";
    readonly description: "[MFLU list] [ZFLU list] [OFLU list] [LEAK] [MIGL] [MRCT list] [ZRCT list] [ORCT list] [MDOS list] [ZDOS list] [ODOS list] [MPOW value1]";
    readonly fragment: "registration";
}, {
    readonly label: "VOL";
    readonly title: "VOL";
    readonly syntax: "VOL …";
    readonly description: "печатается карта VOL с указанием объемов для каждого материал а последовательно,";
    readonly fragment: "burnupRegistration";
}, {
    readonly label: "WOBJ";
    readonly title: "WOBJ";
    readonly syntax: "WOBJ   <массив чисел>";
    readonly description: "<массив чисел> - массив из M действительных чисел, где M – количество регистрационных объектов, заданное в карте NOBJ. Так как эти величины по смыслу являются весами, а не вероятностями, то никаких перенормировок не происходит. Использование регистрационных объектов и их весов требуется только при задании очень сложных источников.";
    readonly fragment: "source";
}, {
    readonly label: "WPHO";
    readonly title: "WPHO";
    readonly syntax: "WPHO valwpho";
    readonly description: "[IWPHN valiwphn] [EGPH valegph1,valegph2] [ELEC valelec] [EGEL valegel1,valegel2] [PSIN valpsin] [PSGR valpsgr] [MATFIL list] [MATPRN] [SIPRN] [DEFPRN] [MATWGT] [MATREP] [VOL V1, V2,..., Vn,..., Vnmat] [STOP]";
    readonly fragment: "physical";
}, {
    readonly label: "WWEN";
    readonly title: "WWEN";
    readonly syntax: "WWEN  <массив границ отрезков>";
    readonly description: "<массив границ отрезков> - массив должен быть упорядочен по возрастанию, энергия вводится в эВ. Любая энергия должна попадать в какой -либо отрезок, поэтому последнее число должно быть очень большим. Число отрезков совпадает с числом введенных чисел, поскольку левая граница первого интервала есть 0. Ценности для отрезков на оси энергии задаются предложением INPE <массив ценностей> <массив ценностей> - массив положительных действительных чисел. Число этих чисел должно быть таким же, как число отрезков. Ценности регистрационных объектов задаются предложением INPO <массив ценностей> <массив ценностей> - массив положительных действительных чисел. Длина этого";
    readonly fragment: "calculationControl";
}, {
    readonly label: "XYZ0";
    readonly title: "XYZ0";
    readonly syntax: "XYZ0  <координаты центра>";
    readonly description: "Если <координаты центра> состоят и трёх чисел, они задают X0 точку в пространстве с помощью координат в основной геометрии. Эта точка будет центром сферической системы координат весовых окон. Использоваться будут лишь расстояния до точки X0 т.е. геометрическое пространство разбивается на сферические слои. Если <координаты центра> состоят и двух чисел, они задают ось OZ цилиндрической системы координат (r,θ,z) в пространстве основной геометрии. Для определения параметров весовых окон использоваться будут лишь координата r, т.е. геометрическое пространство разбивается на цилиндрические слои. RADS <массив радиусов слоёв >";
    readonly fragment: "trajectory";
}, {
    readonly label: "ZCUR";
    readonly title: "ZCUR";
    readonly syntax: "ZCUR list";
    readonly description: "[OCUR list] [MSMT list] [ZSMT list] [OSMT list] [RCT list] [FRM list] [DOS list] [ENERGY list] [SPECTR value] [SFLUX] [DPNT x1,y1,z1,R1,…,xN,yN,zN,RN] [DRING x1,y1,z1,r1,R1,…,xN,yN,zN,rN,RN] [NENRG A, E1,…,EN] [NFUNC A, F1,…,FN] [PENRG A, E1,…,EN] [PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.";
    readonly fragment: "registration";
}, {
    readonly label: "ZDOS";
    readonly title: "ZDOS";
    readonly syntax: "ZDOS …";
    readonly description: "эти карты определяют номера регистрационных областей";
    readonly fragment: "registration";
}, {
    readonly label: "ZELEN";
    readonly title: "ZELEN";
    readonly syntax: "ZELEN list";
    readonly description: "[OELEN list] [NUCOFF] [PERC value1] [FIXED] [NRET value1 value2]";
    readonly fragment: "registration";
}, {
    readonly label: "ZFLU";
    readonly title: "ZFLU";
    readonly syntax: "ZFLU list";
    readonly description: "[OFLU list] [LEAK] [MIGL] [MRCT list] [ZRCT list] [ORCT list] [MDOS list] [ZDOS list] [ODOS list] [MPOW value1]";
    readonly fragment: "registration";
}, {
    readonly label: "ZNEN";
    readonly title: "ZNEN";
    readonly syntax: "ZNEN list";
    readonly description: "[ONEN list] [MPHEN list] [ZPHEN list] [OPHEN list] [MELEN list] [ZELEN list] [OELEN list] [NUCOFF] [PERC value1] [FIXED] [NRET value1 value2]";
    readonly fragment: "registration";
}, {
    readonly label: "ZONP";
    readonly title: "ZONP";
    readonly syntax: "ZONP list";
    readonly description: "Задает значения номеров материалов, для которых результаты расчета изменения изотопного состава выводятся на печать. Информация записывается так же, как для карт FISZ, ABSZ и POWZ. Строка может отсутствовать, в этом случае на печать выводятся характеристики всех материалов. TIMP t1 n1 t2 n2 t3 n3 ... Задает значения времени, при котором выдаются на печать значения концентрации изотопов и их характеристик. Исходные данные записываются так же, как и для опции FINAL. Строка может отсутствовать, в этом случае используются все значения времени. Строка используется только опцией FINTAB. DELTAB выдает результат для всех";
    readonly fragment: "burnup";
}, {
    readonly label: "ZPHEN";
    readonly title: "ZPHEN";
    readonly syntax: "ZPHEN list";
    readonly description: "[OPHEN list] [MELEN list] [ZELEN list] [OELEN list] [NUCOFF] [PERC value1] [FIXED] [NRET value1 value2]";
    readonly fragment: "registration";
}, {
    readonly label: "ZRCT";
    readonly title: "ZRCT";
    readonly syntax: "ZRCT list";
    readonly description: "[ORCT list] [MDOS list] [ZDOS list] [ODOS list] [MPOW value1]";
    readonly fragment: "registration";
}, {
    readonly label: "ZSMT";
    readonly title: "ZSMT";
    readonly syntax: "ZSMT list";
    readonly description: "[OSMT list] [RCT list] [FRM list] [DOS list] [ENERGY list] [SPECTR value] [SFLUX] [DPNT x1,y1,z1,R1,…,xN,yN,zN,RN] [DRING x1,y1,z1,r1,R1,…,xN,yN,zN,rN,RN] [NENRG A, E1,…,EN] [NFUNC A, F1,…,FN] [PENRG A, E1,…,EN] [PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.";
    readonly fragment: "registration";
}];
