/** AUTO-GENERATED by scripts/extract-userguide-cards.mjs — не править вручную */

export const USER_GUIDE_CARDS = [
  {
    "label": "ABSZ",
    "title": "ABSZ",
    "syntax": "ABSZ list",
    "description": "Список материалов типа A. Те же правила ввода, что и для строки FISZ. Может отсутствовать.",
    "fragment": "burnup"
  },
  {
    "label": "ACEPT",
    "title": "ACEPT",
    "syntax": "ACEPT …",
    "description": "включение/выключение в подмодуле FARION для расчёта резонансного",
    "fragment": "physical"
  },
  {
    "label": "ACERR",
    "title": "ACERR",
    "syntax": "ACERR valacerr",
    "description": "[PHOT valphot] [WPHO valwpho] [IWPHN valiwphn] [EGPH valegph1,valegph2] [ELEC valelec] [EGEL valegel1,valegel2] [PSIN valpsin] [PSGR valpsgr] [MATFIL list] [MATPRN] [SIPRN] [DEFPRN] [MATWGT] [MATREP] [VOL V1, V2,..., Vn,..., Vnmat] [STOP]",
    "fragment": "physical"
  },
  {
    "label": "ACTI",
    "title": "ACTI",
    "syntax": "ACTI list",
    "description": "Указание о выводе на печать характеристик продуктов деления. Те же правила ввода, что и для строки CONT.",
    "fragment": "burnup"
  },
  {
    "label": "ADDF",
    "title": "ADDF",
    "syntax": "ADDF file",
    "description": "Определяет название файла file, в котором пользователем задается изот опный состав дополнительного топлива. Единица измерения – число ядер на кубический сантиметр материала в сутки. Формат этого файла ясен из примера на рисунке А.95. PU39 1.739E-06 PU40 8.687E-07 PU41 2.889E-07 Рисунок А.95 – Формат файла задания скорости подпитки Исходные данные опции FINAL 15.2 Опция позволяет получить концентрацию изотопов при временах, не совпадающих с временами, определенными в файле исходных данных VAR.DAT при работе с опцией STEP. В представлении кусочно -линейной зависимости (см отри описание карты COLI)",
    "fragment": "burnup"
  },
  {
    "label": "ADDZ",
    "title": "ADDZ",
    "syntax": "ADDZ m",
    "description": "Определяет номер материала m, в который с постоянной скоростью вводятся новые изотопы. По умолчанию эта строка не задаётся и новые изотопы не вводятся. Очистка и подпитка топлива может выполняться в одном или разных материалах.",
    "fragment": "burnup"
  },
  {
    "label": "BAL",
    "title": "BAL",
    "syntax": "BAL …",
    "description": "при наличии этой карты будут вычисляться функционалы баланса",
    "fragment": "registration"
  },
  {
    "label": "BCRIT",
    "title": "BCRIT",
    "syntax": "BCRIT value",
    "description": "[EABS] [MNEN list] [ZNEN list] [ONEN list] [MPHEN list] [ZPHEN list] [OPHEN list] [MELEN list] [ZELEN list] [OELEN list] [NUCOFF] [PERC value1] [FIXED] [NRET value1 value2]",
    "fragment": "registration"
  },
  {
    "label": "BETA",
    "title": "BETA",
    "syntax": "BETA",
    "description": "При наличии карты вычисляется эффективная доля запаздывающих нейтронов. Редактированию не подлежит.",
    "fragment": "calculationControl"
  },
  {
    "label": "BMAX",
    "title": "BMAX",
    "syntax": "BMAX maxbur",
    "description": "[VOL V1, V2,..., Vn,..., Vnmat] [BUCL value1 value2 value3] FINISH commentary",
    "fragment": "burnupRegistration"
  },
  {
    "label": "BOUN",
    "title": "BOUN",
    "syntax": "BOUN   <mi,ni>   <mj,nj>",
    "description": "Здесь <mi,ni> - пара целых чисел, которые определяют диапазон изменения первого индекса i, <mj,nj> - пара целых чисел, которые определяют диапазон изменения второго индекса j. ROOT <массив из трех чисел> <массив из трех чисел> < массив из трех чисел > Здесь <массив из трех чисел> - это параметры, которые задают три вектора A, B, C. Векторы сдвигов решетки образуются по правилу (Рисунок А.81): ⃗ = ⃗ + i ⃗⃗ + j ⃗ (i = mi, mi + 1,..., ni) (j = mj, mj + 1,..., nj). -1 0 1 2 3 4 5 4 3 2 1 0 A 0 B C Рисунок А.81 – Задание решетки примитивных источников",
    "fragment": "source"
  },
  {
    "label": "BRG",
    "title": "BRG",
    "syntax": "BRG [value1 value2]",
    "description": "BRG – заголовок исходных данных к модулю, первая обязательная карта. value1 - определяет наличие/отсутствие печати карт файла исходных данных в выходном файле (1 – печатать, 0 – не печатать). Значение по умолчанию – 0. value2 - определяет наличие/отсутствие отладочной печати в выходном файле, а при наличии печати также и ее количество (больше 0 – печатать, 0 – не печатать). Значение по умолчанию – 0. Если после заголовка нет ни одной карты, то в этом случае модуль не работает.",
    "fragment": "burnupRegistration"
  },
  {
    "label": "BUCL",
    "title": "BUCL",
    "syntax": "BUCL Bx, By, Bz",
    "description": "[BCRIT value] [EABS] [MNEN list] [ZNEN list] [ONEN list] [MPHEN list] [ZPHEN list] [OPHEN list] [MELEN list] [ZELEN list] [OELEN list] [NUCOFF] [PERC value1] [FIXED] [NRET value1 value2]",
    "fragment": "burnupRegistration"
  },
  {
    "label": "BURALL",
    "title": "BURALL",
    "syntax": "BURALL …",
    "description": "использованием карты BURALL позволяет наиболее полно использовать возможности",
    "fragment": "burnupRegistration"
  },
  {
    "label": "CLEF",
    "title": "CLEF",
    "syntax": "CLEF file",
    "description": "Определяет название файла file, в котором пользователем задается период полувыведения для разны х элементов, который характеризует скорость очистки и является полным аналогом периода полураспада радиоактивных ядер. Формат этого файла ясен из примера на рисунке А.94. Xe 1.0 h Sr 30.0 d Eu 0.2 y Рисунок А.94 – Формат файла задания скорости очистки Введено ограничение: для элементов с временем полувыведения менее 10 часов оно принудительно устанавливается равным 10 часам, а рассчитанная плотность для данного нуклида принудительно устанавливается равной 10–20. Если элемент в file не задан, то он из активной зоны не выводится.",
    "fragment": "burnup"
  },
  {
    "label": "CLEZ",
    "title": "CLEZ",
    "syntax": "CLEZ m",
    "description": "Определяет номер материала m, подлежащего очистке. По умолчанию эта строка не задаётся и очистка не выполняется.",
    "fragment": "burnup"
  },
  {
    "label": "CNTAND",
    "title": "CNTAND",
    "syntax": "CNTAND …",
    "description": "картой CONT в файле исходных данных должна быть использована карта CNTAND.",
    "fragment": "geometry"
  },
  {
    "label": "CODE",
    "title": "CODE",
    "syntax": "CODE option",
    "description": "Определяет название используемой опции работы модуля. Наличие этой строки обязательно. option – может принимать следующие значения:  RSTP – используется опция STEP;",
    "fragment": "burnup"
  },
  {
    "label": "COLI",
    "title": "COLI",
    "syntax": "COLI …",
    "description": "В представлении кусочно -линейной зависимости (см отри описание карты COLI)",
    "fragment": "burnup"
  },
  {
    "label": "CONT",
    "title": "CONT",
    "syntax": "CONT list",
    "description": "Указание о выводе на печать характеристик всех изотопов. Список list содержит указатели для вывода характеристик:  DENS – концентрация;  SIGM – макроскопическое сечение.  CURI – активность;  HEAT – энерговыделение при радиоактивном распаде;  HGAM – энергия гамма квантов при радиоактивном распаде;  HBET – энергия тормозного излучения электронов и позитронов при радиоактивном распаде  QUOT – объем воды, нужный для разбавления изотопа до допустимой концентрации;  SPNU – число нейтронов спонтанного деления и (alpha,n) реакции; Элементы списка могут следовать в произвольном порядке; любой элемент может",
    "fragment": "geometry"
  },
  {
    "label": "CPM",
    "title": "CPM",
    "syntax": "CPM …",
    "description": "физического модуля добавлены карты CPM и CPMEND для обозначения начала и конца",
    "fragment": "physical"
  },
  {
    "label": "DEF",
    "title": "DEF",
    "syntax": "DEF …",
    "description": "Все карты DEF должны располагаться в разделе данных для физического модуля.",
    "fragment": "physical"
  },
  {
    "label": "DEFPRN",
    "title": "DEFPRN",
    "syntax": "DEFPRN …",
    "description": "печатаются параметры нуклидов с учетом переопределений, сделанных",
    "fragment": "physical"
  },
  {
    "label": "DELN",
    "title": "DELN",
    "syntax": "DELN valdeln",
    "description": "[ACEPT] [ACERR valacerr] [PHOT valphot] [WPHO valwpho] [IWPHN valiwphn] [EGPH valegph1,valegph2] [ELEC valelec] [EGEL valegel1,valegel2] [PSIN valpsin] [PSGR valpsgr] [MATFIL list] [MATPRN] [SIPRN] [DEFPRN] [MATWGT] [MATREP] [VOL V1, V2,..., Vn,..., Vnmat] [STOP]",
    "fragment": "registration"
  },
  {
    "label": "DOS",
    "title": "DOS",
    "syntax": "DOS list",
    "description": "[ENERGY list] [SPECTR value] [SFLUX] [DPNT x1,y1,z1,R1,…,xN,yN,zN,RN] [DRING x1,y1,z1,r1,R1,…,xN,yN,zN,rN,RN] [NENRG A, E1,…,EN] [NFUNC A, F1,…,FN] [PENRG A, E1,…,EN] [PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.",
    "fragment": "registration"
  },
  {
    "label": "DPNT",
    "title": "DPNT",
    "syntax": "DPNT x1,y1,z1,R1,…,xN,yN,zN,RN",
    "description": "[DRING x1,y1,z1,r1,R1,…,xN,yN,zN,rN,RN] [NENRG A, E1,…,EN] [NFUNC A, F1,…,FN] [PENRG A, E1,…,EN] [PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.",
    "fragment": "registration"
  },
  {
    "label": "DRING",
    "title": "DRING",
    "syntax": "DRING x1,y1,z1,r1,R1,…,xN,yN,zN,rN,RN",
    "description": "[NENRG A, E1,…,EN] [NFUNC A, F1,…,FN] [PENRG A, E1,…,EN] [PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.",
    "fragment": "registration"
  },
  {
    "label": "DTZM",
    "title": "DTZM",
    "syntax": "DTZM nser",
    "description": "nser - количество серий, через которое накопленная информация записывается в файл задачи; может редактироваться в процессе счета.",
    "fragment": "calculationControl"
  },
  {
    "label": "EABS",
    "title": "EABS",
    "syntax": "EABS …",
    "description": "при наличии этой карты вычисляется средняя энергия поглощения",
    "fragment": "registration"
  },
  {
    "label": "ECEL",
    "title": "ECEL",
    "syntax": "ECEL e1",
    "description": "Указывается граница энергии электрона в электронвольтах, ниже которой траектории прерываются. Область изменения параметра оп ределяется диапазоном работы фотонного подмодуля, заданным в разделе исходных данных для физического модуля. Значение по умолчанию – 100 эВ. Может редактироваться в процессе счета. Управление неаналоговым моделированием 14.2 Допустимо использование нескольких а льтернативных методов неаналогового моделирования. Какой из них будет использован определяется ключами генерации. Для нейтронов и фотонов используется один и тот же метод, но парметры для разных типов частиц могут быть разными.",
    "fragment": "calculationControl"
  },
  {
    "label": "ECPO",
    "title": "ECPO",
    "syntax": "ECPO e1",
    "description": "Нижняя граница энергии позитрона (эВ); траектории ниже прерываются. Аналог ECUT/ECUP/ECEL для позитронов. По умолчанию как у электронов — 100 эВ. Редактируется в процессе счёта.",
    "fragment": "calculationControl"
  },
  {
    "label": "ECUP",
    "title": "ECUP",
    "syntax": "ECUP e1",
    "description": "Указывается граница энергии фотона в электронвольтах, ниже которой траектории прерываются. Область изменения параметра определяется диапазоном работы фотонного подмодуля, заданным в разделе исходных данных для физического модуля. Значение по умолчанию – 10000 эВ. Может редактироваться в процессе счета.",
    "fragment": "calculationControl"
  },
  {
    "label": "ECUT",
    "title": "ECUT",
    "syntax": "ECUT e1",
    "description": "Указывается граница энергии нейтрона в электронвольтах, ниже которой траектории прерываются. Область изменения параметра определяется диапазоном работы нейтронных подмодулей, заданных в разделе исходных данных для физического модуля. Значение по умолчанию – 0 эВ. Может редактироваться в процессе счета.",
    "fragment": "calculationControl"
  },
  {
    "label": "EDIS",
    "title": "EDIS",
    "syntax": "EDIS …",
    "description": "случайной величины одинаковы и равны числу NE из карты EDIS или NM из карты MDIS,",
    "fragment": "source"
  },
  {
    "label": "EGEL",
    "title": "EGEL",
    "syntax": "EGEL valegel1,valegel2",
    "description": "[PSIN valpsin] [PSGR valpsgr] [MATFIL list] [MATPRN] [SIPRN] [DEFPRN] [MATWGT] [MATREP] [VOL V1, V2,..., Vn,..., Vnmat] [STOP]",
    "fragment": "physical"
  },
  {
    "label": "EGPH",
    "title": "EGPH",
    "syntax": "EGPH valegph1,valegph2",
    "description": "[ELEC valelec] [EGEL valegel1,valegel2] [PSIN valpsin] [PSGR valpsgr] [MATFIL list] [MATPRN] [SIPRN] [DEFPRN] [MATWGT] [MATREP] [VOL V1, V2,..., Vn,..., Vnmat] [STOP]",
    "fragment": "physical"
  },
  {
    "label": "EGRC",
    "title": "EGRC",
    "syntax": "EGRC …",
    "description": "имя управляющего массива параметров, определяющего энергетические",
    "fragment": "physical"
  },
  {
    "label": "ELEC",
    "title": "ELEC",
    "syntax": "ELEC valelec",
    "description": "[EGEL valegel1,valegel2] [PSIN valpsin] [PSGR valpsgr] [MATFIL list] [MATPRN] [SIPRN] [DEFPRN] [MATWGT] [MATREP] [VOL V1, V2,..., Vn,..., Vnmat] [STOP]",
    "fragment": "physical"
  },
  {
    "label": "EMES",
    "title": "EMES",
    "syntax": "EMES   <массив значений узлов>",
    "description": "MMES <массив значений узлов> <массив значений узлов> - действительные числа, определяющие узлы возможных значений величины Е в карте EMES или узлы возможных значений величины  в карте MMES. Значения узлов всегд а вводят в порядке возрастания. Значения Е всегда неотрицательны, значения  могут меняться от –1 до 1 (как косинус угла). Массивы вероятностей вводятся с помощью карт: EPRO <массив значений вероятностей> MPRO <массив значений вероятностей> <массив значений вероятностей> - действительные числа, определяющие значения вероятностей для величины Е в карте EPRO или значения вероятностей для величины  в",
    "fragment": "source"
  },
  {
    "label": "END",
    "title": "END",
    "syntax": "END …",
    "description": "имя карты окончания описания материала. Эта карта может быть"
  },
  {
    "label": "ENERGY",
    "title": "ENERGY",
    "syntax": "ENERGY list",
    "description": "[SPECTR value] [SFLUX] [DPNT x1,y1,z1,R1,…,xN,yN,zN,RN] [DRING x1,y1,z1,r1,R1,…,xN,yN,zN,rN,RN] [NENRG A, E1,…,EN] [NFUNC A, F1,…,FN] [PENRG A, E1,…,EN] [PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.",
    "fragment": "registration"
  },
  {
    "label": "ENSO",
    "title": "ENSO",
    "syntax": "ENSO <число>",
    "description": "FINISH X,Y,Z - координаты точки источника, задаваемые в сантиметрах. За начало координат принимается начало отсчета, определенное в данных к геометрическому модулю. <массив из 27 чисел> - числа определяют границы энергетических интервалов, данных в убывающем порядке. Энергия задается в электронвольтах. В результате работы источника",
    "fragment": "source"
  },
  {
    "label": "EOPT",
    "title": "EOPT",
    "syntax": "EOPT opt",
    "description": "Устанавливается способ задания значения энерговыделения при делении, opt может принимать значения: 0 – эффективная энергия, 1 – сумма энергий реакций деления и радиационного захвата. Строка может отсутствовать. Значение по умолчанию равно 0.",
    "fragment": "burnup"
  },
  {
    "label": "EPRO",
    "title": "EPRO",
    "syntax": "EPRO   <массив значений вероятностей>",
    "description": "MPRO <массив значений вероятностей> <массив значений вероятностей> - действительные числа, определяющие значения вероятностей для величины Е в карте EPRO или значения вероятностей для величины  в карте MPRO. Данные, содержащиеся во всех этих массивах, зависят от характеристик спектра, заданного в картах ANGLEN, EDIS, MDIS. Возможны следующие варианты задания параметров в картах дополнительных данных для дискретного и линейного распределений. а) Независимые случайные величины с дискретным распределением (параметр NO или отсутствие этого параметра в карте ANGLEN, параметр D в картах EDIS, MDIS)",
    "fragment": "source"
  },
  {
    "label": "EPSM",
    "title": "EPSM",
    "syntax": "EPSM eps",
    "description": "eps – минимальное значение концентрации изотопов при передаче информации в MCU. Если концентрация изотопа меньше, чем eps, то в MCU этот изотоп не передается. Если eps = 0, передаются все изотопы с концентрацией, отличной от нуля. Если eps < 0, передаются все изотопы, в том числе и с концентрацией, равной нулю. Строка может отсутствовать, в этом случае используется стандартн ое значение (eps=0.0), задаваемое при генерации модуля.",
    "fragment": "burnup"
  },
  {
    "label": "ESET",
    "title": "ESET",
    "syntax": "ESET <массив из 27 чисел>",
    "description": "[SPEC <массив из 26 чисел>] [ENSO <число>] FINISH X,Y,Z - координаты точки источника, задаваемые в сантиметрах. За начало координат принимается начало отсчета, определенное в данных к геометрическому модулю. <массив из 27 чисел> - числа определяют границы энергетических интервалов, данных в убывающем порядке. Энергия задается в электронвольтах. В результате работы источника",
    "fragment": "source"
  },
  {
    "label": "FINISH",
    "title": "FINISH",
    "syntax": "FINISH [commentary]",
    "description": "Здесь FINISH - признак окончания ввода данных к физическому модулю. commentary - текст произвольного содержания. Коррекция данных с помощью файлов PDC 8.10 При работе с исходными данными для физическ ого модуля возможно выполнить коррекцию некоторых данных с помощью внешних текстовых файлов с расширениями вида PDCn (PIN Data Correction), где n может принимать значения от 1 до 9 или отсутствовать (соответствует n=0). При наличии таких фалов в папке с ра счетом их обработка выполняется автоматически. Обработка производится в порядке увеличения n, т.е. в первую очередь будет обработан файл с расширением PDC, а в последнюю – PDC9."
  },
  {
    "label": "FISP",
    "title": "FISP",
    "syntax": "FISP list",
    "description": "Указание о выводе на печать характеристик продуктов деления. Те же правила, что и для строки CONT.",
    "fragment": "burnup"
  },
  {
    "label": "FISZ",
    "title": "FISZ",
    "syntax": "FISZ list",
    "description": "Список материалов типа F. Параметр list определяет номера материалов типа F. Номера материалов в списке list указываются интервалами. Нечетные числа обозначают начала интервалов, четные – их окончания. На рисунке А.88 приведены примеры задания материалов с типом F. Пример 1. Тип F задан для материала 3. FISZ 3 Пример 2. Тип F задан для материала 3. FISZ 3 3 Пример 3. Тип F задан для материалов 3, с 5 по 8, 15. FISZ 3 3, 5 8, 15 Рисунок А.88 – Примеры задания типа материала",
    "fragment": "burnup"
  },
  {
    "label": "FIXED",
    "title": "FIXED",
    "syntax": "FIXED …",
    "description": "при наличии этой карты создается файл, содержащий результаты работы",
    "fragment": "registration"
  },
  {
    "label": "GLIB",
    "title": "GLIB",
    "syntax": "GLIB library",
    "description": "Задает названия библиотеки выходов гамма-квантов. library – имя библиотеки, записанной в файле с указанным именем. При отсутствии этого параметра, расчет производится со стандартной библиотекой. Имя стандартной библиотеки задается при генерации модуля. Исходные данные опций FINTAB и DELTAB 15.4 Опция FINTAB предназначена для постобработки и печати результатов работы STEP и FINAL. Выводятся результаты последнего обращения к FINAL, а если обращения не было, то результаты опции STEP. Постобработка включает в себя расчет следующих интегральных характ еристик материалов и системы в целом:  мощность, кВт;",
    "fragment": "burnup"
  },
  {
    "label": "HEAD",
    "title": "HEAD",
    "syntax": "HEAD [<целое число 1>[<целое число 2>[<целое число 3>]]]",
    "description": "Обязательной в этом предложении является только метка HEAD. <целое число 1> принимает значения 0,1,2,3,4 (значение по умолчанию есть 1):",
    "fragment": "geometry"
  },
  {
    "label": "HGRI",
    "title": "HGRI",
    "syntax": "HGRI   <массив чисел>",
    "description": "<массив чисел> - массив действительных чисел, задающий положения hi Если Nh <0, то вводятся Nh возможных значений высоты: h1 < h2 <...< hM; (M = Nh) Если Nh >0, то вводятся концы Nh отрезков: h0 < h1 < h2 <...< hM. Внутри каждого из этих отрезков случайная величина равномерно распределена. HPC <массив чисел> <массив чисел> - массив из пар чисел ( vi,fi). Числа vi означают реальные интенсивности моделируемого источника. Числа fi означают с точностью до множителя вероятности, с которыми будут генерироваться частицы. Два следующих предложения определяют распределение ri и зависимость весов от",
    "fragment": "source"
  },
  {
    "label": "HPC",
    "title": "HPC",
    "syntax": "HPC   <массив чисел>",
    "description": "<массив чисел> - массив из пар чисел ( vi,fi). Числа vi означают реальные интенсивности моделируемого источника. Числа fi означают с точностью до множителя вероятности, с которыми будут генерироваться частицы. Два следующих предложения определяют распределение ri и зависимость весов от r. RGRI <массив чисел> <массив чисел> - массив действительных чисел, задающий положения ri.",
    "fragment": "source"
  },
  {
    "label": "ICE",
    "title": "ICE",
    "syntax": "ICE list",
    "description": "ICE - имя заголовка раздела; list – список элементов, подлежащих разложению на изотопы. [ICENOT list]",
    "fragment": "physical"
  },
  {
    "label": "ICENOT",
    "title": "ICENOT",
    "syntax": "ICENOT list",
    "description": "ICENOT - имя заголовка раздела; list – список элементов, не подлежащих разложению на изотопы. Список действует с момента его объявления. Можно использовать любое количество карт разложения на изотопы. Это позволяет задавать разложение на изотопы независимо для каждого материала. Можно использовать карту без указания списка. В этом случае с этого м омента разложение на изотопы не производится. Разложение на изотопы производится в соответствии с данными файла ICE.LIB банка данных, который добавлен в MDBFR61. Для разложения на изотопы всех элементов, рекомендуется использовать строку «ICENOT AAAA».",
    "fragment": "physical"
  },
  {
    "label": "INPE",
    "title": "INPE",
    "syntax": "INPE  <массив ценностей>",
    "description": "<массив ценностей> - массив положительных действительных чисел. Число этих чисел должно быть таким же, как число отрезков. Ценности регистрационных объектов задаются предложением INPO <массив ценностей> <массив ценностей> - массив положительных действительных чисел. Длина этого массива может не совпадать с реальным числом регистрационных объектов. Если длина массива меньше этого числа, недостающие позиции заполняются единицами. Режим расщепления/рулетки включается в файл параметров с расширением MEM по ключу +SPLRUL. Режим не совмещается с режимом весового окна и с режимом поверхностного источника.",
    "fragment": "calculationControl"
  },
  {
    "label": "INPM",
    "title": "INPM",
    "syntax": "INPM  < массив из NR*NE чисел >",
    "description": "<массив из NR*NE чисел> – массив понимается как матрица VEij вводимая по строкам и определяющая ценности по радиусам и энергиям. SANG < массив косинусов > <массив косинусов> – вводится массив их NA -1 чисел -1<s1<s2<…<sNA-1<1 Определяет разбиение пространства по углам. (NА-1 - размерность массива). INRA < массив из NR*NA чисел > <массив из NR*NA чисел> – массив понимается как матрица VA размерности NR*NA, вводимая по строкам. Последние 2 предложения могут отсутствовать. При отсут ствии этих карт зависимость от направления полёта отсутствует. При угловом разбиении и сферической системе координат весовые окна",
    "fragment": "trajectory"
  },
  {
    "label": "INPO",
    "title": "INPO",
    "syntax": "INPO  <массив ценностей>",
    "description": "<массив ценностей> - массив положительных действительных чисел. Длина этого массива может не совпадать с реальным числом регистрационных объектов. Если длина массива меньше этого числа, недостающие позиции заполняются единицами. Режим расщепления/рулетки включается в файл параметров с расширением MEM по ключу +SPLRUL. Режим не совмещается с режимом весового окна и с режимом поверхностного источника.",
    "fragment": "calculationControl"
  },
  {
    "label": "INRA",
    "title": "INRA",
    "syntax": "INRA  < массив из NR*NA чисел >",
    "description": "<массив из NR*NA чисел> – массив понимается как матрица VA размерности NR*NA, вводимая по строкам. Последние 2 предложения могут отсутствовать. При отсут ствии этих карт зависимость от направления полёта отсутствует. При угловом разбиении и сферической системе координат весовые окна определены следующим алгоритмом. Пусть точка фазового пространства имеет координаты (X,E,U). X – геометрическое положение, E – энергия, U – направление полёта. Числа j, k, n определены так, что выполнены соотношения: Тогда параметр w m окна определён выражением w m=1/(VEjkVAjn) и w i=wm/ci, ws=wi/cs. При использовании цилиндрической системы используются те же самые формулы,",
    "fragment": "trajectory"
  },
  {
    "label": "ISTR",
    "title": "ISTR",
    "syntax": "ISTR istr",
    "description": "Число istr определяет тип решаемой задачи. По умолчанию istr = 0. В этом случае решается задача о критичности системы и вычисляется эффективный коэффициент размножения. При istr = 1 решается задача с заданным внешним источником. При istr = 2 решается задача с заданным внешним источником и блокируется использование нейтронов деления. Этот режим предназначен для задач, в которых используется рассчитанная каким-то другим методом плотность нейтронов деления.",
    "fragment": "trajectory"
  },
  {
    "label": "IWPHN",
    "title": "IWPHN",
    "syntax": "IWPHN valiwphn",
    "description": "[EGPH valegph1,valegph2] [ELEC valelec] [EGEL valegel1,valegel2] [PSIN valpsin] [PSGR valpsgr] [MATFIL list] [MATPRN] [SIPRN] [DEFPRN] [MATWGT] [MATREP] [VOL V1, V2,..., Vn,..., Vnmat] [STOP]",
    "fragment": "physical"
  },
  {
    "label": "KEFF",
    "title": "KEFF",
    "syntax": "KEFF …",
    "description": "(необходимо наличие карты KEFF) для value значений параметра Bz (необходимо наличие",
    "fragment": "registration"
  },
  {
    "label": "LATT",
    "title": "LATT",
    "syntax": "LATT   <имя генератора сдвигов>",
    "description": "Здесь <имя генератора сдвигов> - S2AR Структура дальнейших строк зависит от используемого генератора сдвигов. В настоящее время реализован только один такой генератор, называющийся S2AR, исходные данные для которого будут описаны. Этот генератор соответствует правильной параллелограммной решетке, подобной генерируемой генератором сдвигов G2AR в модуле NCG. Входные данные состоят из следующих строк. BOUN <mi,ni> <mj,nj> Здесь <mi,ni> - пара целых чисел, которые определяют диапазон изменения первого индекса i, <mj,nj> - пара целых чисел, которые определяют диапазон изменения второго индекса j."
  },
  {
    "label": "LIFE",
    "title": "LIFE",
    "syntax": "LIFE …",
    "description": "при наличии этой карты будет рассчитываться среднее время жизни",
    "fragment": "registration"
  },
  {
    "label": "LIST",
    "title": "LIST",
    "syntax": "LIST list",
    "description": "PARA list В строке LIST задается список изотопов, а в строке PARA задаются их характеристики. Элемент в списке строки LIST задается его химическим символом, а изотоп – в обозначениях MCU. Характеристики в списке строки PARA задаются по тем же правилам, что и для карты CONT. При отсутствии этой карты на печать выводится только концентрация (DENS). На рисунке А.96 приведены примеры задания списка изотопов картой LIST.",
    "fragment": "burnup"
  },
  {
    "label": "MATFIL",
    "title": "MATFIL",
    "syntax": "MATFIL list",
    "description": "[MATPRN] [SIPRN] [DEFPRN] [MATWGT] [MATREP] [VOL V1, V2,..., Vn,..., Vnmat] [STOP]",
    "fragment": "physical"
  },
  {
    "label": "MATPRN",
    "title": "MATPRN",
    "syntax": "MATPRN …",
    "description": "по окончании ввода для каждого материала в формате исходных",
    "fragment": "physical"
  },
  {
    "label": "MATR",
    "title": "MATR",
    "syntax": "MATR …",
    "description": "пропущена, если следующей картой является карта MATR или карта FINISH.",
    "fragment": "physical"
  },
  {
    "label": "MATREP",
    "title": "MATREP",
    "syntax": "MATREP …",
    "description": "осуществляет замену состава всех материалов на первый из отоп",
    "fragment": "physical"
  },
  {
    "label": "MATWGT",
    "title": "MATWGT",
    "syntax": "MATWGT …",
    "description": "рассчитывается вес каждого материала в граммах. Готовится",
    "fragment": "physical"
  },
  {
    "label": "MAXS",
    "title": "MAXS",
    "syntax": "MAXS maxser",
    "description": "maxser –номер серии, после которой счет прекращается; может редактироваться в процессе счета. При наличии ненулевого количества отбрасываемых серий (карта NSKI) параметр maxser определяет число регистрируемых серий, т. е. счет окончится после моделирования числа серий, равного сумме параметров карт NSKI и MAXS.",
    "fragment": "calculationControl"
  },
  {
    "label": "MCUR",
    "title": "MCUR",
    "syntax": "MCUR list",
    "description": "[ZCUR list] [OCUR list] [MSMT list] [ZSMT list] [OSMT list] [RCT list] [FRM list] [DOS list] [ENERGY list] [SPECTR value] [SFLUX] [DPNT x1,y1,z1,R1,…,xN,yN,zN,RN] [DRING x1,y1,z1,r1,R1,…,xN,yN,zN,rN,RN] [NENRG A, E1,…,EN] [NFUNC A, F1,…,FN] [PENRG A, E1,…,EN] [PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.",
    "fragment": "registration"
  },
  {
    "label": "MDOS",
    "title": "MDOS",
    "syntax": "MDOS …",
    "description": "эти карты определяют номера регистрационных областей",
    "fragment": "registration"
  },
  {
    "label": "MELEN",
    "title": "MELEN",
    "syntax": "MELEN list",
    "description": "[ZELEN list] [OELEN list] [NUCOFF] [PERC value1] [FIXED] [NRET value1 value2]",
    "fragment": "registration"
  },
  {
    "label": "MFLU",
    "title": "MFLU",
    "syntax": "MFLU list",
    "description": "[ZFLU list] [OFLU list] [LEAK] [MIGL] [MRCT list] [ZRCT list] [ORCT list] [MDOS list] [ZDOS list] [ODOS list] [MPOW value1]",
    "fragment": "registration"
  },
  {
    "label": "MIR",
    "title": "MIR",
    "syntax": "MIR …",
    "description": "1,-1,0 1",
    "fragment": "geometry"
  },
  {
    "label": "MIXG",
    "title": "MIXG",
    "syntax": "MIXG nmixg",
    "description": "Карта управляет нормализацией поколений в многопроцессорном режиме. При nmixg = 0 нормализация выполняется независимо на каждом процессоре, что соответствует стандартной идеологии распараллеливания расчетов MCU. При n mixg отличном от нуля после, того как все процессоры промоделировали одно поколение нейтронов, выполняется сбор данных по всем процессорам, общая нормализация и раздача нормализованных данных процессорам. Таким образом, в этом режиме многопроцессорный расчет полностью аналогичен по идеологии обычному однопроцессорному расчету. По умолчанию nmixg = 0. FINISH Признак конца фрагмента.",
    "fragment": "trajectory"
  },
  {
    "label": "MMES",
    "title": "MMES",
    "syntax": "MMES  <массив значений узлов>",
    "description": "<массив значений узлов> - действительные числа, определяющие узлы возможных значений величины Е в карте EMES или узлы возможных значений величины  в карте MMES. Значения узлов всегд а вводят в порядке возрастания. Значения Е всегда неотрицательны, значения  могут меняться от –1 до 1 (как косинус угла). Массивы вероятностей вводятся с помощью карт: EPRO <массив значений вероятностей> MPRO <массив значений вероятностей> <массив значений вероятностей> - действительные числа, определяющие значения вероятностей для величины Е в карте EPRO или значения вероятностей для величины  в карте MPRO. Данные, содержащиеся во всех этих массивах, зависят от характеристик спектра,",
    "fragment": "source"
  },
  {
    "label": "MNEN",
    "title": "MNEN",
    "syntax": "MNEN list",
    "description": "[ZNEN list] [ONEN list] [MPHEN list] [ZPHEN list] [OPHEN list] [MELEN list] [ZELEN list] [OELEN list] [NUCOFF] [PERC value1] [FIXED] [NRET value1 value2]",
    "fragment": "registration"
  },
  {
    "label": "MOM4",
    "title": "MOM4",
    "syntax": "MOM4 …",
    "description": "при наличии этой карты помимо первого и второго центральных",
    "fragment": "registration"
  },
  {
    "label": "MPHEN",
    "title": "MPHEN",
    "syntax": "MPHEN list",
    "description": "[ZPHEN list] [OPHEN list] [MELEN list] [ZELEN list] [OELEN list] [NUCOFF] [PERC value1] [FIXED] [NRET value1 value2]",
    "fragment": "registration"
  },
  {
    "label": "MPRO",
    "title": "MPRO",
    "syntax": "MPRO   <массив значений вероятностей>",
    "description": "<массив значений вероятностей> - действительные числа, определяющие значения вероятностей для величины Е в карте EPRO или значения вероятностей для величины  в карте MPRO. Данные, содержащиеся во всех этих массивах, зависят от характеристик спектра, заданного в картах ANGLEN, EDIS, MDIS. Возможны следующие варианты задания параметров в картах дополнительных данных для дискретного и линейного распределений. а) Независимые случайные величины с дискретным распределением (параметр NO или отсутствие этого параметра в карте ANGLEN, параметр D в картах EDIS, MDIS) Длины <массива значений узлов> и <массива значений вероятностей> для каждой",
    "fragment": "source"
  },
  {
    "label": "MRCT",
    "title": "MRCT",
    "syntax": "MRCT list",
    "description": "[ZRCT list] [ORCT list] [MDOS list] [ZDOS list] [ODOS list] [MPOW value1]",
    "fragment": "registration"
  },
  {
    "label": "NAMV",
    "title": "NAMV",
    "syntax": "NAMV namvar",
    "description": "namvar - название варианта; текстовая переменная длиной не более 12 символов; редактированию не подлежит.",
    "fragment": "calculationControl"
  },
  {
    "label": "NBAT",
    "title": "NBAT",
    "syntax": "NBAT nbatch",
    "description": "Каждые последовательные nbatch поколений частиц, называемых сериями, считаются независимыми. По умолчанию nbatch = 3. Точность расчета статистических ошибок рассчитываемых функционалов возрастает с увеличением nbatch.",
    "fragment": "trajectory"
  },
  {
    "label": "NENRG",
    "title": "NENRG",
    "syntax": "NENRG A, E1,…,EN",
    "description": "[NFUNC A, F1,…,FN] [PENRG A, E1,…,EN] [PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.",
    "fragment": "registration"
  },
  {
    "label": "NET",
    "title": "NET",
    "syntax": "NET  <имя сети>   <корневой вектор> <число столбцов>",
    "description": "<число строк>[<число слоев>]",
    "fragment": "geometry"
  },
  {
    "label": "NEUT",
    "title": "NEUT",
    "syntax": "NEUT valneut",
    "description": "EGRC valegrc1, valegrc2, valegrc3 [DELN valdeln] [ACEPT] [ACERR valacerr] [PHOT valphot] [WPHO valwpho] [IWPHN valiwphn] [EGPH valegph1,valegph2] [ELEC valelec] [EGEL valegel1,valegel2] [PSIN valpsin] [PSGR valpsgr] [MATFIL list] [MATPRN] [SIPRN] [DEFPRN] [MATWGT] [MATREP] [VOL V1, V2,..., Vn,..., Vnmat] [STOP]",
    "fragment": "physical"
  },
  {
    "label": "NFUNC",
    "title": "NFUNC",
    "syntax": "NFUNC A, F1,…,FN",
    "description": "[PENRG A, E1,…,EN] [PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.",
    "fragment": "registration"
  },
  {
    "label": "NPRI",
    "title": "NPRI",
    "syntax": "NPRI nhys",
    "description": "nhys - количество историй, через которое на экран будет поступать информационная строка; может редактироваться в процессе счета. BETA При наличии этой карты вычисляется эффективная доля запаздывающих нейтронов; редактированию не подлежит.",
    "fragment": "calculationControl"
  },
  {
    "label": "NRAN",
    "title": "NRAN",
    "syntax": "NRAN n",
    "description": "Параметр, управляющий началом выборки случайных чисел; используется для продолжения расчетов при фатальных авостах; для продолжения счета нужно вновь",
    "fragment": "calculationControl"
  },
  {
    "label": "NRET",
    "title": "NRET",
    "syntax": "NRET value1 value2",
    "description": "KEFF – при наличии этой карты будет рассчитываться эффективный коэффициент размножения нейтронов в рассчитываемой системе.",
    "fragment": "registration"
  },
  {
    "label": "NSKI",
    "title": "NSKI",
    "syntax": "NSKI nski",
    "description": "Число отбрасываемых серий, т. е. серий, не учитываемых при накоплен ии статистики. По умолчанию nski = 0. WTOB w1, w2, ... , wkobj Данная карта предназначена для использования при корректировке числа нейтронов деления на один акт деления (однако распространяется на все типы моделируемых частиц). Карта содержит массив wi, где i соответствует номеру регистрационного объекта. Каждое wi есть неотрицательное число, на которое умножается вес любой вторичной частицы, рожденной в регистрационном объекте i, перед помещением ее в банк. При wi=0 вторичные частицы , рожденные в регис трационном",
    "fragment": "trajectory"
  },
  {
    "label": "NTOT",
    "title": "NTOT",
    "syntax": "NTOT ntot",
    "description": "Число частиц в поколении. По умолчанию ntot = 200. Систематическая ошибка расчета функционалов убывает обратно пропорционально ntot.",
    "fragment": "trajectory"
  },
  {
    "label": "NUCOFF",
    "title": "NUCOFF",
    "syntax": "NUCOFF …",
    "description": "при наличии этой карты регистрация скоростей реакций для нуклидов в",
    "fragment": "registration"
  },
  {
    "label": "OCUR",
    "title": "OCUR",
    "syntax": "OCUR list",
    "description": "[MSMT list] [ZSMT list] [OSMT list] [RCT list] [FRM list] [DOS list] [ENERGY list] [SPECTR value] [SFLUX] [DPNT x1,y1,z1,R1,…,xN,yN,zN,RN] [DRING x1,y1,z1,r1,R1,…,xN,yN,zN,rN,RN] [NENRG A, E1,…,EN] [NFUNC A, F1,…,FN] [PENRG A, E1,…,EN] [PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.",
    "fragment": "registration"
  },
  {
    "label": "ODOS",
    "title": "ODOS",
    "syntax": "ODOS …",
    "description": "эти карты определяют номера регистрационных областей",
    "fragment": "registration"
  },
  {
    "label": "OELEN",
    "title": "OELEN",
    "syntax": "OELEN list",
    "description": "[NUCOFF] [PERC value1] [FIXED] [NRET value1 value2]",
    "fragment": "registration"
  },
  {
    "label": "OFLU",
    "title": "OFLU",
    "syntax": "OFLU list",
    "description": "[LEAK] [MIGL] [MRCT list] [ZRCT list] [ORCT list] [MDOS list] [ZDOS list] [ODOS list] [MPOW value1]",
    "fragment": "registration"
  },
  {
    "label": "ONEN",
    "title": "ONEN",
    "syntax": "ONEN list",
    "description": "[MPHEN list] [ZPHEN list] [OPHEN list] [MELEN list] [ZELEN list] [OELEN list] [NUCOFF] [PERC value1] [FIXED] [NRET value1 value2]",
    "fragment": "registration"
  },
  {
    "label": "OPHEN",
    "title": "OPHEN",
    "syntax": "OPHEN list",
    "description": "[MELEN list] [ZELEN list] [OELEN list] [NUCOFF] [PERC value1] [FIXED] [NRET value1 value2]",
    "fragment": "registration"
  },
  {
    "label": "ORCT",
    "title": "ORCT",
    "syntax": "ORCT …",
    "description": "эти карты определяют номера регистрационных областей",
    "fragment": "registration"
  },
  {
    "label": "PARA",
    "title": "PARA",
    "syntax": "PARA list",
    "description": "В строке LIST задается список изотопов, а в строке PARA задаются их характеристики. Элемент в списке строки LIST задается его химическим символом, а изотоп – в обозначениях MCU. Характеристики в списке строки PARA задаются по тем же правилам, что и для карты CONT. При отсутствии этой карты на печать выводится только концентрация (DENS). На рисунке А.96 приведены примеры задания списка изотопов картой LIST.",
    "fragment": "burnup"
  },
  {
    "label": "PARM",
    "title": "PARM",
    "syntax": "PARM …",
    "description": "P0XY,-P0XY,2.5 /2 -P0XY,P0XY,2.5 P0XY,P0XY,2.5",
    "fragment": "geometry"
  },
  {
    "label": "PBUR",
    "title": "PBUR",
    "syntax": "PBUR extention",
    "description": "Определяет расширение файла PARAMETE.*, хранящегося в библиотеке констант в директории BURN6. Данные файлы содержат цепочки превращения нуклидов в ходе выгорания при разных реакциях взаимодействия с нейтронами и выходы продуктов деления для быстрого ( PARAMETE.FST) и теплового ( PARAMETE.THR) спектров нейтронов. Наличие этой стро ки необязательно, если используется файл, имя которого задано при генерации модуля, т.е. значение по умолчанию. extention – может принимать значения FST или THR. Умалчиваемое значение – THR. По умолчанию расчетный код «настроен» на тепловые реакторы, для р асчета быстрых систем необходимо воспользоваться картой PBUR со значением FST.",
    "fragment": "burnup"
  },
  {
    "label": "PENRG",
    "title": "PENRG",
    "syntax": "PENRG A, E1,…,EN",
    "description": "[PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.",
    "fragment": "registration"
  },
  {
    "label": "PERC",
    "title": "PERC",
    "syntax": "PERC …",
    "description": "Примечание. Карты PERC, FIXED, NRET используются только на этапе финальной",
    "fragment": "registration"
  },
  {
    "label": "PFUNC",
    "title": "PFUNC",
    "syntax": "PFUNC A, F1,…,FN",
    "description": "END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.",
    "fragment": "registration"
  },
  {
    "label": "PHOT",
    "title": "PHOT",
    "syntax": "PHOT valphot",
    "description": "[WPHO valwpho] [IWPHN valiwphn] [EGPH valegph1,valegph2] [ELEC valelec] [EGEL valegel1,valegel2] [PSIN valpsin] [PSGR valpsgr] [MATFIL list] [MATPRN] [SIPRN] [DEFPRN] [MATWGT] [MATREP] [VOL V1, V2,..., Vn,..., Vnmat] [STOP]",
    "fragment": "physical"
  },
  {
    "label": "PIN",
    "title": "PIN",
    "syntax": "PIN [value1 value2]",
    "description": "Здесь PIN - имя карты — заголовка фрагмента; value1 - определяет наличие /отсутствие печати карт файла исходных данных в выходном файле (1 – печатать, 0 – не печатать). Значение по умолчанию — 0. value2 - определяет наличие/отсутствие отладочной печати в выходном файле, а при наличии печати также и ее количество (0 – не печатать, 1,2,… – печатать). Значение по умолчанию — 0. При значении этого параметра равном",
    "fragment": "physical"
  },
  {
    "label": "POWE",
    "title": "POWE",
    "syntax": "POWE q",
    "description": "Устанавливается режим работы \"заданная мощность\" и, одновременно задается суммарное по всем материалам энерговыделение q. Данная карта является, по сут и, картой POWE опции STEP в которой используется только первое значение мощности, а последующие значения времени и мощности игнорируются. Единицы измерения: q – кВт. BSEC t BMIN t BHOU t BDAY t Эти строки задают время t работы на мощности q для расчета и вывода на печать концентрации изотопов и данных о запаздывающем излучении. Единицы измерения, соответственно, BSEC – секунда, BMIN – минута, BHOU – час, BDAY – сутки. Опция требует наличия карты STEP, хотя и не использует ее значений.",
    "fragment": "burnup"
  },
  {
    "label": "POWZ",
    "title": "POWZ",
    "syntax": "POWZ list",
    "description": "Список материалов типа P. Те же правила ввода, что и для раздела FISZ. Может отсутствовать. Одна из строк FISZ или ABSZ со списком материалов должна присутствовать обязательно, иначе будет выдано сообщение об ошибке. POWE q1 t1 q2 t2 q3 t3 ... Устанавливается режим работы \"заданная мощность\" и, одновременно задается суммарное по всем материалам энерговыделение Q в зависимости от времени T. Единицы измерения: Q – кВт, T – сутки. Q(T) представляется как кусочно -постоянная функция и вводится парами чисел q (энерговыделение на данном временном интервале) и t (верхняя граница временного интервала).",
    "fragment": "burnup"
  },
  {
    "label": "PRISOU",
    "title": "PRISOU",
    "syntax": "PRISOU …",
    "description": "Карта PRISOU включает печать внутренних массивов модуля источников.",
    "fragment": "source"
  },
  {
    "label": "PSGR",
    "title": "PSGR",
    "syntax": "PSGR valpsgr",
    "description": "[MATFIL list] [MATPRN] [SIPRN] [DEFPRN] [MATWGT] [MATREP] [VOL V1, V2,..., Vn,..., Vnmat] [STOP]",
    "fragment": "physical"
  },
  {
    "label": "PSIN",
    "title": "PSIN",
    "syntax": "PSIN valpsin",
    "description": "[PSGR valpsgr] [MATFIL list] [MATPRN] [SIPRN] [DEFPRN] [MATWGT] [MATREP] [VOL V1, V2,..., Vn,..., Vnmat] [STOP]",
    "fragment": "physical"
  },
  {
    "label": "PTYPE",
    "title": "PTYPE",
    "syntax": "PTYPE …",
    "description": "обязательная первая карта раздела.",
    "fragment": "registration"
  },
  {
    "label": "RADS",
    "title": "RADS",
    "syntax": "RADS  <массив радиусов слоёв >",
    "description": "<массив радиусов слоёв> – массив действительных, положительных чисел: r1<r2<…<rNR. (NR- размерность массива). 1-ый слой определён неравенством 0rr1, j-ый слой определён неравенством rj-1<rrj. INPM < массив из NR*NE чисел > <массив из NR*NE чисел> – массив понимается как матрица VEij вводимая по строкам и определяющая ценности по радиусам и энергиям. SANG < массив косинусов > <массив косинусов> – вводится массив их NA -1 чисел -1<s1<s2<…<sNA-1<1 Определяет разбиение пространства по углам. (NА-1 - размерность массива). INRA < массив из NR*NA чисел > <массив из NR*NA чисел> – массив понимается как матрица VA размерности",
    "fragment": "trajectory"
  },
  {
    "label": "RCT",
    "title": "RCT",
    "syntax": "RCT list",
    "description": "[FRM list] [DOS list] [ENERGY list] [SPECTR value] [SFLUX] [DPNT x1,y1,z1,R1,…,xN,yN,zN,RN] [DRING x1,y1,z1,r1,R1,…,xN,yN,zN,rN,RN] [NENRG A, E1,…,EN] [NFUNC A, F1,…,FN] [PENRG A, E1,…,EN] [PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.",
    "fragment": "registration"
  },
  {
    "label": "RCZD",
    "title": "RCZD",
    "syntax": "RCZD …",
    "description": "означает цилиндр с внутренним распределением вероятностей рождения.",
    "fragment": "source"
  },
  {
    "label": "REPER",
    "title": "REPER",
    "syntax": "REPER  <массив параметров>",
    "description": "<массив параметров>:  три действительных числа, задающие координаты постоянного реперного вектора, который нормируется на свою длину.  /P и три действительных числа, которые задают координаты характерной точки системы ⃗ (положение индикатора). В этом случае при рождении частицы реперный вектор в точке рождения определяется по формуле ⃗p = ( ⃗ – ⃗) ( ⃗ – ⃗, ⃗ – ⃗)-0.5  число 1 либо минус 1, которое определяет знак нормали, то есть sgn. При каждой генерации точки рождения примитивный источник вырабатывает зависящий от этой точки вектор нормали к контейнеру vn . Реперный вектор определяется по формуле",
    "fragment": "source"
  },
  {
    "label": "RGRI",
    "title": "RGRI",
    "syntax": "RGRI   <массив чисел>",
    "description": "<массив чисел> - массив действительных чисел, задающий положения ri.",
    "fragment": "source"
  },
  {
    "label": "RGS",
    "title": "RGS",
    "syntax": "RGS [value1 value2]",
    "description": "RGS - имя карты — заголовка фрагмента; value1 - определяет наличие/отсутствие печати карт файла исходных данных в выходном файле (1 – печатать, 0 – не печатать). Значение по умолчанию — 0. value2 - определяет наличие/отсутствие отладочной печати в выходном файле, а при наличии печати также и ее количество (больше 0 – печатать, 0 – не печатать). Значение по умолчанию — 0.",
    "fragment": "registration"
  },
  {
    "label": "SANG",
    "title": "SANG",
    "syntax": "SANG  < массив косинусов >",
    "description": "<массив косинусов> – вводится массив их NA -1 чисел -1<s1<s2<…<sNA-1<1 Определяет разбиение пространства по углам. (NА-1 - размерность массива). INRA < массив из NR*NA чисел > <массив из NR*NA чисел> – массив понимается как матрица VA размерности NR*NA, вводимая по строкам. Последние 2 предложения могут отсутствовать. При отсут ствии этих карт зависимость от направления полёта отсутствует. При угловом разбиении и сферической системе координат весовые окна определены следующим алгоритмом. Пусть точка фазового пространства имеет координаты (X,E,U). X – геометрическое положение, E – энергия, U – направление полёта.",
    "fragment": "trajectory"
  },
  {
    "label": "SETT",
    "title": "SETT",
    "syntax": "SETT np",
    "description": "Управляющий параметр np может принимать значения N, PH , EL, PO. (по умолчанию np равно N). Значение N означает что все дальнейшие строки данных для неаналогового моделирования относятся к нейтронам, значение PH – к фотонам, EL – к электронам, PO – к позитронам. Таким образом, если решается чисто нейтронная задача, то строка задания типа частицы не нужна.",
    "fragment": "calculationControl"
  },
  {
    "label": "SFLUX",
    "title": "SFLUX",
    "syntax": "SFLUX …",
    "description": "текущем разделе параметров регистрации (карты SFLUX + MCUR, ZCUR и/или OCUR)",
    "fragment": "registration"
  },
  {
    "label": "SI",
    "title": "SI",
    "syntax": "SI list",
    "description": "Здесь SI - имя заголовка раздела; list – список нуклидов, входящих в суммарный изотоп. [SINOT list] Здесь SINOT - имя заголовка раздела; list – список нуклидов, не входящих в суммарный изотоп. [SIDEN value] Здесь SIDEN - имя заголовка раздела; value – все нуклиды с плотностью меньше данного значения входят в суммарный изотоп. Список действует с момента его объявления. Можно использовать любое количество карт описания суммарного изотопа. Это позволяет задавать состав суммарного изотопа независимо для каждого материала. Можно использовать карту без указания списка. В этом случае, считается, что с этого момента суммарный изотоп не содержит",
    "fragment": "physical"
  },
  {
    "label": "SIDEN",
    "title": "SIDEN",
    "syntax": "SIDEN value",
    "description": "Здесь SIDEN - имя заголовка раздела; value – все нуклиды с плотностью меньше данного значения входят в суммарный изотоп. Список действует с момента его объявления. Можно использовать любое количество карт описания суммарного изотопа. Это позволяет задавать состав суммарного изотопа независимо для каждого материала. Можно использовать карту без указания списка. В этом случае, считается, что с этого момента суммарный изотоп не содержит нуклидов. При одно временном наличии перед описанием материала списков SI и SINOT активным является тот, который был объявлен последним. Карта SIDEN активна всегда, независимо от наличия или отсутствия карт SI и",
    "fragment": "physical"
  },
  {
    "label": "SINOT",
    "title": "SINOT",
    "syntax": "SINOT list",
    "description": "Здесь SINOT - имя заголовка раздела; list – список нуклидов, не входящих в суммарный изотоп. [SIDEN value] Здесь SIDEN - имя заголовка раздела; value – все нуклиды с плотностью меньше данного значения входят в суммарный изотоп. Список действует с момента его объявления. Можно использовать любое количество карт описания суммарного изотопа. Это позволяет задавать состав суммарного изотопа независимо для каждого материала. Можно использовать карту без указания списка. В этом случае, считается, что с этого момента суммарный изотоп не содержит нуклидов. При одно временном наличии перед описанием материала списков SI и SINOT",
    "fragment": "physical"
  },
  {
    "label": "SIPRN",
    "title": "SIPRN",
    "syntax": "SIPRN …",
    "description": "для каждого материала печатаются сечения полученн ого суммарного",
    "fragment": "physical"
  },
  {
    "label": "SPEC",
    "title": "SPEC",
    "syntax": "SPEC <массив из 26 чисел>",
    "description": "[ENSO <число>] FINISH X,Y,Z - координаты точки источника, задаваемые в сантиметрах. За начало координат принимается начало отсчета, определенное в данных к геометрическому модулю. <массив из 27 чисел> - числа определяют границы энергетических интервалов, данных в убывающем порядке. Энергия задается в электронвольтах. В результате работы источника",
    "fragment": "source"
  },
  {
    "label": "SPECTR",
    "title": "SPECTR",
    "syntax": "SPECTR value",
    "description": "[SFLUX] [DPNT x1,y1,z1,R1,…,xN,yN,zN,RN] [DRING x1,y1,z1,r1,R1,…,xN,yN,zN,rN,RN] [NENRG A, E1,…,EN] [NFUNC A, F1,…,FN] [PENRG A, E1,…,EN] [PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.",
    "fragment": "registration"
  },
  {
    "label": "SPNT",
    "title": "SPNT",
    "syntax": "SPNT …",
    "description": "Признаком использования простого источника является карта SPNT, которая",
    "fragment": "source"
  },
  {
    "label": "STEP",
    "title": "STEP",
    "syntax": "STEP …",
    "description": "Опция требует наличия карты STEP, хотя и не использует ее значений."
  },
  {
    "label": "STOP",
    "title": "STOP",
    "syntax": "STOP …",
    "description": "останавливает выполнение задачи после окончания чтения исходных"
  },
  {
    "label": "SUMZ",
    "title": "SUMZ",
    "syntax": "SUMZ list",
    "description": "Указание о выводе на печать интегральных характеристик всей системы и отдельных материалов. Список list содержит указатели для вывода характеристик:  SUMB – характеристики выгорания всей системы;  ZONB – характеристики выгорания отдельных материалов;  SUMS – макроскопические сечения всей системы;",
    "fragment": "burnup"
  },
  {
    "label": "TEMPR",
    "title": "TEMPR",
    "syntax": "TEMPR value",
    "description": "TEMPR - имя заголовка раздела; value - значение температуры, константа вещественного типа. Описание суммарного изотопа 8.5 В разделе описания суммарного изотопа задается список нуклидов, входящих в суммарный изотоп. Нуклиды, входящие в суммарный изотоп, обрабатываются иначе, чем нуклиды, не входящ ие в него. В суммарный изотоп обычно помещаются нуклиды, не оказывающие значительного влияния на результаты моделирования конкретной системы. Метод основан на том, что в каждом материале пользователь может заменить малозначащие изотопы (продукты деления и далёкие актиноиды) одним суммарным изотопом с нулевыми сечениями рассеяния и деления и сечениями поглощения и",
    "fragment": "physical"
  },
  {
    "label": "THOU",
    "title": "THOU",
    "syntax": "THOU …",
    "description": "час, TDAY – сутки, TYEA – год. Отсчет времени задается строкой TIMP.",
    "fragment": "burnup"
  },
  {
    "label": "TRANSF",
    "title": "TRANSF",
    "syntax": "TRANSF …",
    "description": "На рисунке А.37 приводится пример использования карты TRANSF."
  },
  {
    "label": "TTYPE",
    "title": "TTYPE",
    "syntax": "TTYPE value1",
    "description": "[MFLU list] [ZFLU list] [OFLU list] [LEAK] [MIGL] [MRCT list] [ZRCT list] [ORCT list] [MDOS list] [ZDOS list] [ODOS list] [MPOW value1]",
    "fragment": "registration"
  },
  {
    "label": "VOL",
    "title": "VOL",
    "syntax": "VOL …",
    "description": "печатается карта VOL с указанием объемов для каждого материал а последовательно,",
    "fragment": "burnupRegistration"
  },
  {
    "label": "WOBJ",
    "title": "WOBJ",
    "syntax": "WOBJ   <массив чисел>",
    "description": "<массив чисел> - массив из M действительных чисел, где M – количество регистрационных объектов, заданное в карте NOBJ. Так как эти величины по смыслу являются весами, а не вероятностями, то никаких перенормировок не происходит. Использование регистрационных объектов и их весов требуется только при задании очень сложных источников.",
    "fragment": "source"
  },
  {
    "label": "WPHO",
    "title": "WPHO",
    "syntax": "WPHO valwpho",
    "description": "[IWPHN valiwphn] [EGPH valegph1,valegph2] [ELEC valelec] [EGEL valegel1,valegel2] [PSIN valpsin] [PSGR valpsgr] [MATFIL list] [MATPRN] [SIPRN] [DEFPRN] [MATWGT] [MATREP] [VOL V1, V2,..., Vn,..., Vnmat] [STOP]",
    "fragment": "physical"
  },
  {
    "label": "WWEN",
    "title": "WWEN",
    "syntax": "WWEN  <массив границ отрезков>",
    "description": "<массив границ отрезков> - массив должен быть упорядочен по возрастанию, энергия вводится в эВ. Любая энергия должна попадать в какой -либо отрезок, поэтому последнее число должно быть очень большим. Число отрезков совпадает с числом введенных чисел, поскольку левая граница первого интервала есть 0. Ценности для отрезков на оси энергии задаются предложением INPE <массив ценностей> <массив ценностей> - массив положительных действительных чисел. Число этих чисел должно быть таким же, как число отрезков. Ценности регистрационных объектов задаются предложением INPO <массив ценностей> <массив ценностей> - массив положительных действительных чисел. Длина этого",
    "fragment": "calculationControl"
  },
  {
    "label": "XYZ0",
    "title": "XYZ0",
    "syntax": "XYZ0  <координаты центра>",
    "description": "Если <координаты центра> состоят и трёх чисел, они задают X0 точку в пространстве с помощью координат в основной геометрии. Эта точка будет центром сферической системы координат весовых окон. Использоваться будут лишь расстояния до точки X0 т.е. геометрическое пространство разбивается на сферические слои. Если <координаты центра> состоят и двух чисел, они задают ось OZ цилиндрической системы координат (r,θ,z) в пространстве основной геометрии. Для определения параметров весовых окон использоваться будут лишь координата r, т.е. геометрическое пространство разбивается на цилиндрические слои. RADS <массив радиусов слоёв >",
    "fragment": "trajectory"
  },
  {
    "label": "ZCUR",
    "title": "ZCUR",
    "syntax": "ZCUR list",
    "description": "[OCUR list] [MSMT list] [ZSMT list] [OSMT list] [RCT list] [FRM list] [DOS list] [ENERGY list] [SPECTR value] [SFLUX] [DPNT x1,y1,z1,R1,…,xN,yN,zN,RN] [DRING x1,y1,z1,r1,R1,…,xN,yN,zN,rN,RN] [NENRG A, E1,…,EN] [NFUNC A, F1,…,FN] [PENRG A, E1,…,EN] [PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.",
    "fragment": "registration"
  },
  {
    "label": "ZDOS",
    "title": "ZDOS",
    "syntax": "ZDOS …",
    "description": "эти карты определяют номера регистрационных областей",
    "fragment": "registration"
  },
  {
    "label": "ZELEN",
    "title": "ZELEN",
    "syntax": "ZELEN list",
    "description": "[OELEN list] [NUCOFF] [PERC value1] [FIXED] [NRET value1 value2]",
    "fragment": "registration"
  },
  {
    "label": "ZFLU",
    "title": "ZFLU",
    "syntax": "ZFLU list",
    "description": "[OFLU list] [LEAK] [MIGL] [MRCT list] [ZRCT list] [ORCT list] [MDOS list] [ZDOS list] [ODOS list] [MPOW value1]",
    "fragment": "registration"
  },
  {
    "label": "ZNEN",
    "title": "ZNEN",
    "syntax": "ZNEN list",
    "description": "[ONEN list] [MPHEN list] [ZPHEN list] [OPHEN list] [MELEN list] [ZELEN list] [OELEN list] [NUCOFF] [PERC value1] [FIXED] [NRET value1 value2]",
    "fragment": "registration"
  },
  {
    "label": "ZONP",
    "title": "ZONP",
    "syntax": "ZONP list",
    "description": "Задает значения номеров материалов, для которых результаты расчета изменения изотопного состава выводятся на печать. Информация записывается так же, как для карт FISZ, ABSZ и POWZ. Строка может отсутствовать, в этом случае на печать выводятся характеристики всех материалов. TIMP t1 n1 t2 n2 t3 n3 ... Задает значения времени, при котором выдаются на печать значения концентрации изотопов и их характеристик. Исходные данные записываются так же, как и для опции FINAL. Строка может отсутствовать, в этом случае используются все значения времени. Строка используется только опцией FINTAB. DELTAB выдает результат для всех",
    "fragment": "burnup"
  },
  {
    "label": "ZPHEN",
    "title": "ZPHEN",
    "syntax": "ZPHEN list",
    "description": "[OPHEN list] [MELEN list] [ZELEN list] [OELEN list] [NUCOFF] [PERC value1] [FIXED] [NRET value1 value2]",
    "fragment": "registration"
  },
  {
    "label": "ZRCT",
    "title": "ZRCT",
    "syntax": "ZRCT list",
    "description": "[ORCT list] [MDOS list] [ZDOS list] [ODOS list] [MPOW value1]",
    "fragment": "registration"
  },
  {
    "label": "ZSMT",
    "title": "ZSMT",
    "syntax": "ZSMT list",
    "description": "[OSMT list] [RCT list] [FRM list] [DOS list] [ENERGY list] [SPECTR value] [SFLUX] [DPNT x1,y1,z1,R1,…,xN,yN,zN,RN] [DRING x1,y1,z1,r1,R1,…,xN,yN,zN,rN,RN] [NENRG A, E1,…,EN] [NFUNC A, F1,…,FN] [PENRG A, E1,…,EN] [PFUNC A, F1,…,FN] END В этом разделе карты, начинающиеся с буквы M относятся к материалам, Z — зонам, а O — к объектам.",
    "fragment": "registration"
  }
] as const;
