"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isBodyRefInHits = exports.resolveBodyRef = exports.cellPitchFromContainer = exports.netPrototypeAt = exports.resolveNetCell = exports.parseGltlPlacements = exports.computeSceneBbox = exports.buildSliceGrid = exports.queryPoint = exports.buildGeometryContext = exports.sliceAtZ = exports.buildScene = exports.isGlobalScope = exports.emptyBbox = exports.buildVars = exports.buildPrimitive = exports.bboxUnion = exports.pointInBodyNode = exports.pointInBody = exports.evalZoneExpr = exports.collectBodyRefs = exports.parseZoneExpression = exports.colorForZone = exports.colorForMaterial = exports.colorForBody = void 0;
var colors_1 = require("./colors");
Object.defineProperty(exports, "colorForBody", { enumerable: true, get: function () { return colors_1.colorForBody; } });
Object.defineProperty(exports, "colorForMaterial", { enumerable: true, get: function () { return colors_1.colorForMaterial; } });
Object.defineProperty(exports, "colorForZone", { enumerable: true, get: function () { return colors_1.colorForZone; } });
var zoneExpression_1 = require("./zoneExpression");
Object.defineProperty(exports, "parseZoneExpression", { enumerable: true, get: function () { return zoneExpression_1.parseZoneExpression; } });
Object.defineProperty(exports, "collectBodyRefs", { enumerable: true, get: function () { return zoneExpression_1.collectBodyRefs; } });
Object.defineProperty(exports, "evalZoneExpr", { enumerable: true, get: function () { return zoneExpression_1.evalZoneExpr; } });
var pointInBody_1 = require("./pointInBody");
Object.defineProperty(exports, "pointInBody", { enumerable: true, get: function () { return pointInBody_1.pointInBody; } });
Object.defineProperty(exports, "pointInBodyNode", { enumerable: true, get: function () { return pointInBody_1.pointInBodyNode; } });
var primitives_1 = require("./primitives");
Object.defineProperty(exports, "bboxUnion", { enumerable: true, get: function () { return primitives_1.bboxUnion; } });
Object.defineProperty(exports, "buildPrimitive", { enumerable: true, get: function () { return primitives_1.buildPrimitive; } });
Object.defineProperty(exports, "buildVars", { enumerable: true, get: function () { return primitives_1.buildVars; } });
Object.defineProperty(exports, "emptyBbox", { enumerable: true, get: function () { return primitives_1.emptyBbox; } });
Object.defineProperty(exports, "isGlobalScope", { enumerable: true, get: function () { return primitives_1.isGlobalScope; } });
var buildScene_1 = require("./buildScene");
Object.defineProperty(exports, "buildScene", { enumerable: true, get: function () { return buildScene_1.buildScene; } });
Object.defineProperty(exports, "sliceAtZ", { enumerable: true, get: function () { return buildScene_1.sliceAtZ; } });
var query_1 = require("./query");
Object.defineProperty(exports, "buildGeometryContext", { enumerable: true, get: function () { return query_1.buildGeometryContext; } });
Object.defineProperty(exports, "queryPoint", { enumerable: true, get: function () { return query_1.queryPoint; } });
Object.defineProperty(exports, "buildSliceGrid", { enumerable: true, get: function () { return query_1.buildSliceGrid; } });
Object.defineProperty(exports, "computeSceneBbox", { enumerable: true, get: function () { return query_1.computeSceneBbox; } });
var gltl_1 = require("./gltl");
Object.defineProperty(exports, "parseGltlPlacements", { enumerable: true, get: function () { return gltl_1.parseGltlPlacements; } });
var netQuery_1 = require("./netQuery");
Object.defineProperty(exports, "resolveNetCell", { enumerable: true, get: function () { return netQuery_1.resolveNetCell; } });
Object.defineProperty(exports, "netPrototypeAt", { enumerable: true, get: function () { return netQuery_1.netPrototypeAt; } });
Object.defineProperty(exports, "cellPitchFromContainer", { enumerable: true, get: function () { return netQuery_1.cellPitchFromContainer; } });
var bodyRefs_1 = require("./bodyRefs");
Object.defineProperty(exports, "resolveBodyRef", { enumerable: true, get: function () { return bodyRefs_1.resolveBodyRef; } });
Object.defineProperty(exports, "isBodyRefInHits", { enumerable: true, get: function () { return bodyRefs_1.isBodyRefInHits; } });
//# sourceMappingURL=index.js.map